#ifndef ELECTRICUSENSOR_HPP_INCLUDED
#define ELECTRICUSENSOR_HPP_INCLUDED

#include <iostream>
#include "ComponentEssentials.h"
#include "ComponentUtilities.h"
#include "math.h"

//!
//! @file ElectricUsensor.hpp
//! @author Petter Krus <petter.krus@liu.se>
//! @date Tue 31 Jan 2012 15:03:09
//! @brief Sensor of electric voltage
//! @ingroup ElectricComponents
//!
//This component is generated by COMPGEN for HOPSAN-NG simulation 
//from 
/*{, C:, Documents and Settings, petkr14, My Documents, \
CompgenNG}/ElectricNG.nb*/

using namespace hopsan;

class ElectricUsensor : public ComponentSignal
{
private:
     Port *mpPel1;
     Port *mpPuout;
     int mNstep;
     //Port Pel1 variable
     double uel1;
     double iel1;
     double cel1;
     double Zcel1;
     //inputVariables
     //outputVariables
     double uout;

     //Expressions variables

     //Port Pel1 pointer
     double *mpND_uel1;
     double *mpND_iel1;
     double *mpND_cel1;
     double *mpND_Zcel1;
     //Delay declarations
     //inputVariables pointers
     //outputVariables pointers
     double *mpND_uout;

public:
     static Component *Creator()
     {
        return new ElectricUsensor();
     }

     void configure()
     {

        mNstep=9;

        //Add ports to the component
        mpPel1=addReadPort("Pel1","NodeElectric");

        //Add inputVariables ports to the component

        //Add outputVariables ports to the component
        mpPuout=addWritePort("Puout","NodeSignal", Port::NotRequired);

        //Register changable parameters to the HOPSAN++ core
     }

    void initialize()
     {
        //Read port variable pointers from nodes
        //Port Pel1
        mpND_uel1=getSafeNodeDataPtr(mpPel1, NodeElectric::Voltage);
        mpND_iel1=getSafeNodeDataPtr(mpPel1, NodeElectric::Current);
        mpND_cel1=getSafeNodeDataPtr(mpPel1, NodeElectric::WaveVariable);
        mpND_Zcel1=getSafeNodeDataPtr(mpPel1, NodeElectric::CharImpedance);
        //Read inputVariables pointers from nodes
        //Read outputVariable pointers from nodes
        mpND_uout=getSafeNodeDataPtr(mpPuout, NodeSignal::Value);

        //Read variables from nodes
        //Port Pel1
        uel1 = (*mpND_uel1);
        iel1 = (*mpND_iel1);
        cel1 = (*mpND_cel1);
        Zcel1 = (*mpND_Zcel1);

        //Read inputVariables from nodes

        //Read outputVariables from nodes
        uout = mpPuout->getStartValue(NodeSignal::Value);



        //Initialize delays

     }
    void simulateOneTimestep()
     {
        //Read variables from nodes
        //Port Pel1
        uel1 = (*mpND_uel1);
        iel1 = (*mpND_iel1);

        //Read inputVariables from nodes

        //LocalExpressions

          //Expressions
          uout = uel1;

        //Calculate the delayed parts


        //Write new values to nodes

        (*mpND_uout)=uout;

        //Update the delayed variabels

     }
};
#endif // ELECTRICUSENSOR_HPP_INCLUDED
