#ifndef HYDRAULICCENTRIFUGALPUMPJ_HPP_INCLUDED
#define HYDRAULICCENTRIFUGALPUMPJ_HPP_INCLUDED

#include <iostream>
#include "ComponentEssentials.h"
#include "ComponentUtilities.h"
#include "math.h"

//!
//! @file HydraulicCentrifugalPumpJ.hpp
//! @author Petter Krus <petter.krus@liu.se>
//! @date Mon 4 Feb 2013 00:02:38
//! @brief Centrifugal pump
//! @ingroup HydraulicComponents
//!
//This component is generated by COMPGEN for HOPSAN-NG simulation 
//from 
/*{, C:, Users, petkr14.IEI, Documents, \
CompgenNG}/HydraulicComponentsNG3.nb*/

using namespace hopsan;

class HydraulicCentrifugalPumpJ : public ComponentQ
{
private:
     double mkl;
     double mb;
     double md;
     double mbeta2;
     double mAp;
     double mrho;
     double mKcp;
     double mBp;
     double mJp;
     double mpcav;
     Port *mpP1;
     Port *mpP2;
     Port *mpPmr1;
     Port *mpPq2e;
     Port *mpPPin;
     Port *mpPPout;
     double delayParts1[9];
     double delayParts2[9];
     double delayParts3[9];
     double delayParts4[9];
     double delayParts5[9];
     Matrix jacobianMatrix;
     Vec systemEquations;
     Matrix delayedPart;
     int i;
     int iter;
     int mNoiter;
     double jsyseqnweight[4];
     int order[5];
     int mNstep;
     //Port P1 variable
     double p1;
     double q1;
     double T1;
     double dE1;
     double c1;
     double Zc1;
     //Port P2 variable
     double p2;
     double q2;
     double T2;
     double dE2;
     double c2;
     double Zc2;
     //Port Pmr1 variable
     double tormr1;
     double thetamr1;
     double wmr1;
     double cmr1;
     double Zcmr1;
     double eqInertiamr1;
     //inputVariables
     //outputVariables
     double q2e;
     double Pin;
     double Pout;

     //Expressions variables
     //Port P1 pointer
     double *mpND_p1;
     double *mpND_q1;
     double *mpND_T1;
     double *mpND_dE1;
     double *mpND_c1;
     double *mpND_Zc1;
     //Port P2 pointer
     double *mpND_p2;
     double *mpND_q2;
     double *mpND_T2;
     double *mpND_dE2;
     double *mpND_c2;
     double *mpND_Zc2;
     //Port Pmr1 pointer
     double *mpND_tormr1;
     double *mpND_thetamr1;
     double *mpND_wmr1;
     double *mpND_cmr1;
     double *mpND_Zcmr1;
     double *mpND_eqInertiamr1;
     //Delay declarations
     //inputVariables pointers
     //outputVariables pointers
     double *mpND_q2e;
     double *mpND_Pin;
     double *mpND_Pout;
     Delay mDelayedPart10;
     Delay mDelayedPart20;
     Delay mDelayedPart21;
     EquationSystemSolver *mpSolver;

public:
     static Component *Creator()
     {
        return new HydraulicCentrifugalPumpJ();
     }

     void configure()
     {
        const double kl = 0.8;
        const double b = 0.03;
        const double d = 0.3;
        const double beta2 = 1.57;
        const double Ap = 0.001;
        const double rho = 860;
        const double Kcp = 1.e-11;
        const double Bp = 1.;
        const double Jp = 0.1;
        const double pcav = 100.;

        mNstep=9;
        jacobianMatrix.create(5,5);
        systemEquations.create(5);
        delayedPart.create(6,6);
        mNoiter=2;
        jsyseqnweight[0]=1;
        jsyseqnweight[1]=0.67;
        jsyseqnweight[2]=0.5;
        jsyseqnweight[3]=0.5;

        mkl = kl;
        mb = b;
        md = d;
        mbeta2 = beta2;
        mAp = Ap;
        mrho = rho;
        mKcp = Kcp;
        mBp = Bp;
        mJp = Jp;
        mpcav = pcav;

        //Add ports to the component
        mpP1=addPowerPort("P1","NodeHydraulic");
        mpP2=addPowerPort("P2","NodeHydraulic");
        mpPmr1=addPowerPort("Pmr1","NodeMechanicRotational");

        //Add inputVariables ports to the component

        //Add outputVariables ports to the component
        mpPq2e=addWritePort("Pq2e","NodeSignal", Port::NotRequired);
        mpPPin=addWritePort("PPin","NodeSignal", Port::NotRequired);
        mpPPout=addWritePort("PPout","NodeSignal", Port::NotRequired);

        //Register changable parameters to the HOPSAN++ core
        registerParameter("kl", "Flow loss koeff.", "", mkl);
        registerParameter("b", "outlet axial width", "m", mb);
        registerParameter("d", "Diameter", "m", md);
        registerParameter("beta2", "Outlet flow angle", "rad", mbeta2);
        registerParameter("Ap", "outlet flow area", "m2", mAp);
        registerParameter("rho", "Fluid density", "kg/m2", mrho);
        registerParameter("Kcp", "Leakage coeff", "m3/s/Pa", mKcp);
        registerParameter("Bp", "Visc friction coeff", "N/m/s", mBp);
        registerParameter("Jp", "Visc friction coeff", "N/m/s", mJp);
        registerParameter("pcav", "cavitaion pressure", "Pa", mpcav);
        mpSolver = new EquationSystemSolver(this,5);
     }

    void initialize()
     {
        //Read port variable pointers from nodes
        //Port P1
        mpND_p1=getSafeNodeDataPtr(mpP1, NodeHydraulic::Pressure);
        mpND_q1=getSafeNodeDataPtr(mpP1, NodeHydraulic::Flow);
        mpND_T1=getSafeNodeDataPtr(mpP1, NodeHydraulic::Temperature);
        mpND_dE1=getSafeNodeDataPtr(mpP1, NodeHydraulic::HeatFlow);
        mpND_c1=getSafeNodeDataPtr(mpP1, NodeHydraulic::WaveVariable);
        mpND_Zc1=getSafeNodeDataPtr(mpP1, NodeHydraulic::CharImpedance);
        //Port P2
        mpND_p2=getSafeNodeDataPtr(mpP2, NodeHydraulic::Pressure);
        mpND_q2=getSafeNodeDataPtr(mpP2, NodeHydraulic::Flow);
        mpND_T2=getSafeNodeDataPtr(mpP2, NodeHydraulic::Temperature);
        mpND_dE2=getSafeNodeDataPtr(mpP2, NodeHydraulic::HeatFlow);
        mpND_c2=getSafeNodeDataPtr(mpP2, NodeHydraulic::WaveVariable);
        mpND_Zc2=getSafeNodeDataPtr(mpP2, NodeHydraulic::CharImpedance);
        //Port Pmr1
        mpND_tormr1=getSafeNodeDataPtr(mpPmr1, \
NodeMechanicRotational::Torque);
        mpND_thetamr1=getSafeNodeDataPtr(mpPmr1, \
NodeMechanicRotational::Angle);
        mpND_wmr1=getSafeNodeDataPtr(mpPmr1, \
NodeMechanicRotational::AngularVelocity);
        mpND_cmr1=getSafeNodeDataPtr(mpPmr1, \
NodeMechanicRotational::WaveVariable);
        mpND_Zcmr1=getSafeNodeDataPtr(mpPmr1, \
NodeMechanicRotational::CharImpedance);
        mpND_eqInertiamr1=getSafeNodeDataPtr(mpPmr1, \
NodeMechanicRotational::EquivalentInertia);
        //Read inputVariables pointers from nodes
        //Read outputVariable pointers from nodes
        mpND_q2e=getSafeNodeDataPtr(mpPq2e, NodeSignal::VALUE);
        mpND_Pin=getSafeNodeDataPtr(mpPPin, NodeSignal::VALUE);
        mpND_Pout=getSafeNodeDataPtr(mpPPout, NodeSignal::VALUE);

        //Read variables from nodes
        //Port P1
        p1 = (*mpND_p1);
        q1 = (*mpND_q1);
        T1 = (*mpND_T1);
        dE1 = (*mpND_dE1);
        c1 = (*mpND_c1);
        Zc1 = (*mpND_Zc1);
        //Port P2
        p2 = (*mpND_p2);
        q2 = (*mpND_q2);
        T2 = (*mpND_T2);
        dE2 = (*mpND_dE2);
        c2 = (*mpND_c2);
        Zc2 = (*mpND_Zc2);
        //Port Pmr1
        tormr1 = (*mpND_tormr1);
        thetamr1 = (*mpND_thetamr1);
        wmr1 = (*mpND_wmr1);
        cmr1 = (*mpND_cmr1);
        Zcmr1 = (*mpND_Zcmr1);
        eqInertiamr1 = (*mpND_eqInertiamr1);

        //Read inputVariables from nodes

        //Read outputVariables from nodes
        q2e = mpPq2e->getStartValue(NodeSignal::VALUE);
        Pin = mpPPin->getStartValue(NodeSignal::VALUE);
        Pout = mpPPout->getStartValue(NodeSignal::VALUE);



        //Initialize delays
        delayParts2[1] = (1.*Power(mAp,2)*mKcp*mTimestep*Power(p1,2) - \
2.*Power(mAp,2)*mKcp*mTimestep*p1*p2 + \
1.*Power(mAp,2)*mKcp*mTimestep*Power(p2,2) - \
0.5*mKcp*mkl*mrho*mTimestep*p1*Power(q2,2) + \
0.5*mKcp*mkl*mrho*mTimestep*p2*Power(q2,2) - 1.*Power(mAp,2)*mTimestep*p1*q2e \
+ 1.*Power(mAp,2)*mTimestep*p2*q2e + 0.5*mkl*mrho*mTimestep*Power(q2,2)*q2e - \
0.001*Power(mAp,2)*mTimestep*tormr1 + 0.002*Power(mAp,2)*mJp*wmr1 - \
0.001*Power(mAp,2)*mBp*mTimestep*wmr1 - \
1.*Power(mAp,2)*mTimestep*tormr1*Abs(wmr1) + \
2.*Power(mAp,2)*mJp*wmr1*Abs(wmr1) - \
1.*Power(mAp,2)*mBp*mTimestep*wmr1*Abs(wmr1))/(-0.002*Power(mAp,2)*mJp - \
0.001*Power(mAp,2)*mBp*mTimestep - 2.*Power(mAp,2)*mJp*Abs(wmr1) - \
1.*Power(mAp,2)*mBp*mTimestep*Abs(wmr1));
        mDelayedPart21.initialize(mNstep,delayParts2[1]);

        delayedPart[1][1] = delayParts1[1];
        delayedPart[2][1] = delayParts2[1];
        delayedPart[3][1] = delayParts3[1];
        delayedPart[4][1] = delayParts4[1];
        delayedPart[5][1] = delayParts5[1];
     }
    void simulateOneTimestep()
     {
        Vec stateVar(5);
        Vec stateVark(5);
        Vec deltaStateVar(5);

        //Read variables from nodes
        //Port P1
        T1 = (*mpND_T1);
        c1 = (*mpND_c1);
        Zc1 = (*mpND_Zc1);
        //Port P2
        T2 = (*mpND_T2);
        c2 = (*mpND_c2);
        Zc2 = (*mpND_Zc2);
        //Port Pmr1
        cmr1 = (*mpND_cmr1);
        Zcmr1 = (*mpND_Zcmr1);

        //Read inputVariables from nodes

        //LocalExpressions

        //Initializing variable vector for Newton-Raphson
        stateVark[0] = q2;
        stateVark[1] = wmr1;
        stateVark[2] = p1;
        stateVark[3] = p2;
        stateVark[4] = tormr1;

        //Iterative solution using Newton-Rapshson
        for(iter=1;iter<=mNoiter;iter++)
        {
         //CentrifugalPumpJ
         //Differential-algebraic system of equation parts

          //Assemble differential-algebraic equations
          systemEquations[0] =mKcp*(-p1 + p2) + q2 - mAp*signedSquareL((2*(p1 \
- p2 + (mrho*wmr1*(0.25*mb*Power(md,2)*wmr1 + \
0.159155*mrho*q2*Cot(mbeta2)))/mb))/(mkl*mrho),10.);
          systemEquations[1] =wmr1 + \
(mTimestep*(mkl*mrho*Power(q2,2)*(-0.5*mKcp*p1 + 0.5*mKcp*p2 + 0.5*q2e) + \
Power(mAp,2)*(1.*mKcp*Power(p1,2) - 2.*mKcp*p1*p2 + 1.*mKcp*Power(p2,2) - \
1.*p1*q2e + 1.*p2*q2e - 0.001*tormr1) - \
1.*Power(mAp,2)*tormr1*Abs(wmr1)))/(Power(mAp,2)*(-0.002*mJp - \
0.001*mBp*mTimestep - 2.*mJp*Abs(wmr1) - 1.*mBp*mTimestep*Abs(wmr1))) + \
delayedPart[2][1];
          systemEquations[2] =-c1 + p1 - q1*Zc1;
          systemEquations[3] =-c2 + p2 - q2*Zc2;
          systemEquations[4] =-cmr1 + tormr1 - wmr1*Zcmr1;

          //Jacobian matrix
          jacobianMatrix[0][0] = 1 - \
(0.31831*mAp*mrho*wmr1*Cot(mbeta2)*dxSignedSquareL((2*(p1 - p2 + \
(mrho*wmr1*(0.25*mb*Power(md,2)*wmr1 + \
0.159155*mrho*q2*Cot(mbeta2)))/mb))/(mkl*mrho),10.))/(mb*mkl);
          jacobianMatrix[0][1] = (-2*mAp*(0.25*Power(md,2)*mrho*wmr1 + \
(mrho*(0.25*mb*Power(md,2)*wmr1 + \
0.159155*mrho*q2*Cot(mbeta2)))/mb)*dxSignedSquareL((2*(p1 - p2 + \
(mrho*wmr1*(0.25*mb*Power(md,2)*wmr1 + \
0.159155*mrho*q2*Cot(mbeta2)))/mb))/(mkl*mrho),10.))/(mkl*mrho);
          jacobianMatrix[0][2] = -mKcp - (2*mAp*dxSignedSquareL((2*(p1 - p2 + \
(mrho*wmr1*(0.25*mb*Power(md,2)*wmr1 + \
0.159155*mrho*q2*Cot(mbeta2)))/mb))/(mkl*mrho),10.))/(mkl*mrho);
          jacobianMatrix[0][3] = mKcp + (2*mAp*dxSignedSquareL((2*(p1 - p2 + \
(mrho*wmr1*(0.25*mb*Power(md,2)*wmr1 + \
0.159155*mrho*q2*Cot(mbeta2)))/mb))/(mkl*mrho),10.))/(mkl*mrho);
          jacobianMatrix[0][4] = 0;
          jacobianMatrix[1][0] = (mTimestep*(0. + 2*mkl*mrho*q2*(-0.5*mKcp*p1 \
+ 0.5*mKcp*p2 + 0.5*q2e)))/(Power(mAp,2)*(-0.002*mJp - 0.001*mBp*mTimestep - \
2.*mJp*Abs(wmr1) - 1.*mBp*mTimestep*Abs(wmr1)));
          jacobianMatrix[1][1] = 1 - \
(mTimestep*(mkl*mrho*Power(q2,2)*(-0.5*mKcp*p1 + 0.5*mKcp*p2 + 0.5*q2e) + \
Power(mAp,2)*(1.*mKcp*Power(p1,2) - 2.*mKcp*p1*p2 + 1.*mKcp*Power(p2,2) - \
1.*p1*q2e + 1.*p2*q2e - 0.001*tormr1) - 1.*Power(mAp,2)*tormr1*Abs(wmr1))*(0. \
- 2.*mJp*dxAbs(wmr1) - \
1.*mBp*mTimestep*dxAbs(wmr1)))/(Power(mAp,2)*Power(-0.002*mJp - \
0.001*mBp*mTimestep - 2.*mJp*Abs(wmr1) - 1.*mBp*mTimestep*Abs(wmr1),2)) + \
(mTimestep*(0. - \
1.*Power(mAp,2)*tormr1*dxAbs(wmr1)))/(Power(mAp,2)*(-0.002*mJp - \
0.001*mBp*mTimestep - 2.*mJp*Abs(wmr1) - 1.*mBp*mTimestep*Abs(wmr1)));
          jacobianMatrix[1][2] = 0. + (mTimestep*((0. - \
0.5*mKcp)*mkl*mrho*Power(q2,2) + Power(mAp,2)*(0. + 2.*mKcp*p1 - 2.*mKcp*p2 - \
1.*q2e)))/(Power(mAp,2)*(-0.002*mJp - 0.001*mBp*mTimestep - 2.*mJp*Abs(wmr1) \
- 1.*mBp*mTimestep*Abs(wmr1)));
          jacobianMatrix[1][3] = (mTimestep*(0.5*mKcp*mkl*mrho*Power(q2,2) + \
Power(mAp,2)*(0. - 2.*mKcp*p1 + 2.*mKcp*p2 + \
1.*q2e)))/(Power(mAp,2)*(-0.002*mJp - 0.001*mBp*mTimestep - 2.*mJp*Abs(wmr1) \
- 1.*mBp*mTimestep*Abs(wmr1)));
          jacobianMatrix[1][4] = 0. + (mTimestep*(0. - 0.001*Power(mAp,2) - \
1.*Power(mAp,2)*Abs(wmr1)))/(Power(mAp,2)*(-0.002*mJp - 0.001*mBp*mTimestep - \
2.*mJp*Abs(wmr1) - 1.*mBp*mTimestep*Abs(wmr1)));
          jacobianMatrix[2][0] = 0;
          jacobianMatrix[2][1] = 0;
          jacobianMatrix[2][2] = 1;
          jacobianMatrix[2][3] = 0;
          jacobianMatrix[2][4] = 0;
          jacobianMatrix[3][0] = -Zc2;
          jacobianMatrix[3][1] = 0;
          jacobianMatrix[3][2] = 0;
          jacobianMatrix[3][3] = 1;
          jacobianMatrix[3][4] = 0;
          jacobianMatrix[4][0] = 0;
          jacobianMatrix[4][1] = -Zcmr1;
          jacobianMatrix[4][2] = 0;
          jacobianMatrix[4][3] = 0;
          jacobianMatrix[4][4] = 1;

          //Solving equation using LU-faktorisation
          mpSolver->solve(jacobianMatrix, systemEquations, stateVark, iter);
          q2=stateVark[0];
          wmr1=stateVark[1];
          p1=stateVark[2];
          p2=stateVark[3];
          tormr1=stateVark[4];
          //Expressions
          q1 = -q2;
          Pin = tormr1*wmr1;
          Pout = (-p1 + p2)*q2;
        }

        //Calculate the delayed parts
        delayParts2[1] = (1.*Power(mAp,2)*mKcp*mTimestep*Power(p1,2) - \
2.*Power(mAp,2)*mKcp*mTimestep*p1*p2 + \
1.*Power(mAp,2)*mKcp*mTimestep*Power(p2,2) - \
0.5*mKcp*mkl*mrho*mTimestep*p1*Power(q2,2) + \
0.5*mKcp*mkl*mrho*mTimestep*p2*Power(q2,2) - 1.*Power(mAp,2)*mTimestep*p1*q2e \
+ 1.*Power(mAp,2)*mTimestep*p2*q2e + 0.5*mkl*mrho*mTimestep*Power(q2,2)*q2e - \
0.001*Power(mAp,2)*mTimestep*tormr1 + 0.002*Power(mAp,2)*mJp*wmr1 - \
0.001*Power(mAp,2)*mBp*mTimestep*wmr1 - \
1.*Power(mAp,2)*mTimestep*tormr1*Abs(wmr1) + \
2.*Power(mAp,2)*mJp*wmr1*Abs(wmr1) - \
1.*Power(mAp,2)*mBp*mTimestep*wmr1*Abs(wmr1))/(-0.002*Power(mAp,2)*mJp - \
0.001*Power(mAp,2)*mBp*mTimestep - 2.*Power(mAp,2)*mJp*Abs(wmr1) - \
1.*Power(mAp,2)*mBp*mTimestep*Abs(wmr1));

        delayedPart[1][1] = delayParts1[1];
        delayedPart[2][1] = delayParts2[1];
        delayedPart[3][1] = delayParts3[1];
        delayedPart[4][1] = delayParts4[1];
        delayedPart[5][1] = delayParts5[1];

        //Write new values to nodes
        //Port P1
        (*mpND_p1)=p1;
        (*mpND_q1)=q1;
        (*mpND_dE1)=dE1;
        //Port P2
        (*mpND_p2)=p2;
        (*mpND_q2)=q2;
        (*mpND_dE2)=dE2;
        //Port Pmr1
        (*mpND_tormr1)=tormr1;
        (*mpND_thetamr1)=thetamr1;
        (*mpND_wmr1)=wmr1;
        (*mpND_eqInertiamr1)=eqInertiamr1;
        //outputVariables
        (*mpND_q2e)=q2e;
        (*mpND_Pin)=Pin;
        (*mpND_Pout)=Pout;

        //Update the delayed variabels
        mDelayedPart21.update(delayParts2[1]);

     }
};
#endif // HYDRAULICCENTRIFUGALPUMPJ_HPP_INCLUDED
