@echo off
REM $Id$
REM Batch script for extracting subversion revision number and writing to specified header define file in specified folder.
REM If folder is missing no file is written
REM Author: Peter Nordin peter.nordin@liu.se
REM Date:   2011-10-26
REM For use in Hopsan, requires TortoiseSVN installed

setlocal
REM TODO: Add more potential paths here
set PATH=%PATH%;"C:\Program Files\TortoiseSVN\bin"
set foldername="%~1"
set filename="%~2"
set definename="%~3"

REM -------------------------------------------
set version=""
set versionS=""
REM Find the revision number, the fifth token from the line
for /f "tokens=5" %%i in ('SubWCRev .^|find "Last committed at revision"') do set version=%%i 
REM Remove trailing space
for /f "tokens=1 delims=/ " %%a in ("%version%") do set versionS=%%a

REM If the include folder exists write the svnrevnum.h file to that folder
if exist %foldername% (
  echo writing file
  call :writeFile "%foldername%/%filename%" %definename% %versionS%
)

REM Determine what to report and what exit code to give
REM Exit with code 0 (success) or 1 (failed)
if %versionS%=="" (
  echo "RevisionInformationNotFound"
  exit /b 1
) else (
  echo %versionS%
  exit /b 0
)


:writeFile
  echo //This file has been automatically generated by getSvnRevision.bat > %~1
  echo // $Id >> %~1
  set hguard=%~2_H_INCLUDED
  echo %hguard%
  echo #ifndef %hguard% >> %~1
  echo #define %hguard% >> %~1
  if not "%~3"=="" (
    echo #define %~2 %~3 >> %~1 
  ) else (
    echo #define %~2 UNKNOWN >> %~1
  )
  echo #endif >> %~1
goto:eof
