#!/bin/bash
# $Id$

# Shell script for writing git commit version info to file
# For use in Hopsan
# Author: Peter Nordin peter.nordin@liu.se
# Date:   2017-01-17


filedst="$1"
name="$2"
shorthash="$3"
datedottime="$4"
hguard=${name}GITVERSION_H_INCLUDED


echo "// This file has been automatically generated by $0" > ${filedst}
echo "// \$Id\$" >> ${filedst}
echo "#ifndef" $hguard >> ${filedst}
echo "#define" $hguard >> ${filedst}
echo "#define" ${name}_COMMIT_HASH ${shorthash} >> ${filedst}
echo "#define" ${name}_COMMIT_TIMESTAMP ${datedottime} >> ${filedst}
echo "#endif" >> ${filedst}

