// This file has been automatically generated by writeGitVersionHeader.sh
// $Id$
#ifndef HOPSANCOREGITVERSION_H_INCLUDED
#define HOPSANCOREGITVERSION_H_INCLUDED
#define HOPSANCORE_COMMIT_HASH f6800a955
#define HOPSANCORE_COMMIT_TIMESTAMP 20260217.1325
#endif
