//This file has been automatically generated by generateLibraryFiles.py!
#include "SignalFFBor.hpp"
#include "SignalFFBloop.hpp"
#include "SignalFFB.hpp"
#include "SignalFFBloopIn.hpp"
#include "SignalFFBand.hpp"
#include "SignalFFBorIn.hpp"
#include "SignalFFBandIn.hpp"
