#ifndef HOPSANDEFAULTSIGNALARITHMETICCOMPONENTS_H
#define HOPSANDEFAULTSIGNALARITHMETICCOMPONENTS_H

#include "SignalAdd.hpp"
#include "SignalSubtract.hpp"
#include "SignalMultiply.hpp"
#include "SignalDivide.hpp"
//#include "SignalSin.hpp"
//#include "SignalCos.hpp"
//#include "SignalSinh.hpp"
//#include "SignalCosh.hpp"
//#include "SignalTanh.hpp"
//#include "SignalAsin.hpp"
//#include "SignalAcos.hpp"
//#include "SignalAtan.hpp"
//#include "SignalAtan2.hpp"
//#include "SignalTan.hpp"
//#include "SignalLog.hpp"
//#include "SignalLog10.hpp"
//#include "SignalSegare.hpp"
#include "SignalSign.hpp"
//#include "SignalSqrt.hpp"
#include "SignalSub.hpp"
//#include "SignalPower.hpp"
#include "SignalGain.hpp"
#include "SignalAbsoluteValue.hpp"
#include "SignalMin.hpp"
#include "SignalMax.hpp"
#include "SignalSum.hpp"
#include "SignalSquare.hpp"

#endif // HOPSANDEFAULTSIGNALARITHMETICCOMPONENTS_H
