disp('Compiling S-function from Hopsan model...');
mex -DWIN32 -DSTATICCORE -DBUILTINDEFAULTCOMPONENTLIB ...
-IHopsanCore/include ...
-IHopsanCore/Dependencies/libcsv_parser++-1.0.0/include/csv_parser ...
-IHopsanCore/Dependencies/rapidxml-1.13 ...
-IcomponentLibraries/defaultLibrary ...
<<<modelname>>>.cpp ...
HopsanCore/src/Component.cc ...
HopsanCore/src/ComponentSystem.cc ...
HopsanCore/src/HopsanEssentials.cc ...
HopsanCore/src/HopsanTypes.cc ...
HopsanCore/src/Node.cc ...
HopsanCore/src/Nodes.cc ...
HopsanCore/src/Parameters.cc ...
HopsanCore/src/Port.cc ...
HopsanCore/src/ComponentUtilities/AuxiliarySimulationFunctions.cc ...
HopsanCore/src/ComponentUtilities/CSVParser.cc ...
HopsanCore/src/ComponentUtilities/DoubleIntegratorWithDamping.cc ...
HopsanCore/src/ComponentUtilities/DoubleIntegratorWithDampingAndCoulumbFriction.cc ...
HopsanCore/src/ComponentUtilities/EquationSystemSolver.cpp ...
HopsanCore/src/ComponentUtilities/FirstOrderTransferFunction.cc ...
HopsanCore/src/ComponentUtilities/HopsanPowerUser.cc ...
HopsanCore/src/ComponentUtilities/Integrator.cc ...
HopsanCore/src/ComponentUtilities/IntegratorLimited.cc ...
HopsanCore/src/ComponentUtilities/ludcmp.cc ...
HopsanCore/src/ComponentUtilities/matrix.cc ...
HopsanCore/src/ComponentUtilities/SecondOrderTransferFunction.cc ...
HopsanCore/src/ComponentUtilities/TurbulentFlowFunction.cc ...
HopsanCore/src/ComponentUtilities/ValveHysteresis.cc ...
HopsanCore/src/ComponentUtilities/WhiteGaussianNoise.cc ...
HopsanCore/src/CoreUtilities/CoSimulationUtilities.cpp ...
HopsanCore/src/CoreUtilities/GeneratorHandler.cpp ...
HopsanCore/src/CoreUtilities/HmfLoader.cc ...
HopsanCore/src/CoreUtilities/HopsanCoreMessageHandler.cc ...
HopsanCore/src/CoreUtilities/LoadExternal.cc ...
HopsanCore/src/CoreUtilities/MultiThreadingUtilities.cpp ...
HopsanCore/src/CoreUtilities/StringUtilities.cpp ...
HopsanCore/Dependencies/libcsv_parser++-1.0.0/csv_parser.cpp ...
componentLibraries/defaultLibrary/defaultComponentLibraryInternal.cc
disp('Finished.')
