#ifndef AEROTURBYFILTER_HPP_INCLUDED
#define AEROTURBYFILTER_HPP_INCLUDED

#include <iostream>
#include "ComponentEssentials.h"
#include "ComponentUtilities.h"
#include "math.h"

//!
//! @file \
C:\HopsanTrunk\ComponentLibraries\defaultLibrary\Special\AeroComponents\AeroT\
urbYfilter.hpp
//! @author Petter Krus <petter.krus@liu.se>
//! @date Sat 3 May 2014 00:27:31
//! @brief First order low pass filter
//! @ingroup AeroComponents
//!
//==This code has been autogenerated using Compgen==
//from 
/*{, C:, Users, petkr14.IEI, Documents, CompgenNG}/AeroFilters.nb*/

using namespace hopsan;

class AeroTurbYfilter : public ComponentSignal
{
private:
     double sn;
     double Lv;
     double delayParts1[9];
     double delayParts2[9];
     Matrix jacobianMatrix;
     Vec systemEquations;
     Matrix delayedPart;
     int i;
     int iter;
     int mNoiter;
     double jsyseqnweight[4];
     int order[1];
     int mNstep;
//==This code has been autogenerated using Compgen==
     //inputVariables
     double V;
     double noise;
     //outputVariables
     double dv;
     //Delay declarations
//==This code has been autogenerated using Compgen==
     //inputVariables pointers
     double *mpV;
     double *mpnoise;
     //outputVariables pointers
     double *mpdv;
     Delay mDelayedPart10;
     Delay mDelayedPart11;
     Delay mDelayedPart12;
     EquationSystemSolver *mpSolver;

public:
     static Component *Creator()
     {
        return new AeroTurbYfilter();
     }

     void configure()
     {
//==This code has been autogenerated using Compgen==

        mNstep=9;
        jacobianMatrix.create(1,1);
        systemEquations.create(1);
        delayedPart.create(2,6);
        mNoiter=2;
        jsyseqnweight[0]=1;
        jsyseqnweight[1]=0.67;
        jsyseqnweight[2]=0.5;
        jsyseqnweight[3]=0.5;


        //Add ports to the component
        //Add inputVariables to the component
            addInputVariable("V","speed","m/s",100.,&mpV);
            addInputVariable("noise","noise input"," ",0.,&mpnoise);

        //Add outputVariables to the component
            addOutputVariable("dv","turbulence lateral \
speed","m/s",0.,&mpdv);

//==This code has been autogenerated using Compgen==
        //Add constants/parameters
            addConstant("sn", "turbulense intensity", "m/s", 1.,sn);
            addConstant("Lv", "turbulence scale length", "ms/", 525.,Lv);
        mpSolver = new EquationSystemSolver(this,1);
     }

    void initialize()
     {
        //Read port variable pointers from nodes

        //Read variables from nodes

        //Read inputVariables from nodes
        V = (*mpV);
        noise = (*mpnoise);

        //Read outputVariables from nodes
        dv = (*mpdv);

//==This code has been autogenerated using Compgen==


        //Initialize delays
        delayParts1[1] = (-8.*dv*Power(Lv,2) - \
1.5957697955504146*Sqrt(Lv)*Power(mTimestep,2)*noise*sn*Power(Abs(1. + \
V),1.5) + 2.*dv*Power(mTimestep,2)*Power(Abs(1. + V),2))/(4.*Power(Lv,2) + \
4.*Lv*mTimestep*Abs(1. + V) + Power(mTimestep,2)*Power(Abs(1. + V),2));
        mDelayedPart11.initialize(mNstep,delayParts1[1]);
        delayParts1[2] = (4.*dv*Power(Lv,2) + \
2.7639543630771177*Power(Lv,1.5)*mTimestep*noise*sn*Sqrt(Abs(1. + V)) - \
4.*dv*Lv*mTimestep*Abs(1. + V) - \
0.7978848977752073*Sqrt(Lv)*Power(mTimestep,2)*noise*sn*Power(Abs(1. + \
V),1.5) + dv*Power(mTimestep,2)*Power(Abs(1. + V),2))/(4.*Power(Lv,2) + \
4.*Lv*mTimestep*Abs(1. + V) + Power(mTimestep,2)*Power(Abs(1. + V),2));
        mDelayedPart12.initialize(mNstep,delayParts1[2]);

        delayedPart[1][1] = delayParts1[1];
        delayedPart[1][2] = mDelayedPart12.getIdx(1);
     }
    void simulateOneTimestep()
     {
        Vec stateVar(1);
        Vec stateVark(1);
        Vec deltaStateVar(1);

        //Read variables from nodes

        //Read inputVariables from nodes
        V = (*mpV);
        noise = (*mpnoise);

        //LocalExpressions

        //Initializing variable vector for Newton-Raphson
        stateVark[0] = dv;

        //Iterative solution using Newton-Rapshson
        for(iter=1;iter<=mNoiter;iter++)
        {
         //TurbYfilter
         //Differential-algebraic system of equation parts

          //Assemble differential-algebraic equations
          systemEquations[0] =dv + (Sqrt(Lv)*mTimestep*noise*sn*Sqrt(Abs(1. + \
V))*(-2.7639543630771177*Lv - 0.7978848977752073*mTimestep*Abs(1. + \
V)))/(4.*Power(Lv,2) + 4.*Lv*mTimestep*Abs(1. + V) + \
Power(mTimestep,2)*Power(Abs(1. + V),2)) + delayedPart[1][1] + \
delayedPart[1][2];

          //Jacobian matrix
          jacobianMatrix[0][0] = 1.;
//==This code has been autogenerated using Compgen==

          //Solving equation using LU-faktorisation
          mpSolver->solve(jacobianMatrix, systemEquations, stateVark, iter);
          dv=stateVark[0];
        }

        //Calculate the delayed parts
        delayParts1[1] = (-8.*dv*Power(Lv,2) - \
1.5957697955504146*Sqrt(Lv)*Power(mTimestep,2)*noise*sn*Power(Abs(1. + \
V),1.5) + 2.*dv*Power(mTimestep,2)*Power(Abs(1. + V),2))/(4.*Power(Lv,2) + \
4.*Lv*mTimestep*Abs(1. + V) + Power(mTimestep,2)*Power(Abs(1. + V),2));
        delayParts1[2] = (4.*dv*Power(Lv,2) + \
2.7639543630771177*Power(Lv,1.5)*mTimestep*noise*sn*Sqrt(Abs(1. + V)) - \
4.*dv*Lv*mTimestep*Abs(1. + V) - \
0.7978848977752073*Sqrt(Lv)*Power(mTimestep,2)*noise*sn*Power(Abs(1. + \
V),1.5) + dv*Power(mTimestep,2)*Power(Abs(1. + V),2))/(4.*Power(Lv,2) + \
4.*Lv*mTimestep*Abs(1. + V) + Power(mTimestep,2)*Power(Abs(1. + V),2));

        delayedPart[1][1] = delayParts1[1];
        delayedPart[1][2] = mDelayedPart12.getIdx(0);

        //Write new values to nodes
        //outputVariables
        (*mpdv)=dv;

        //Update the delayed variabels
        mDelayedPart11.update(delayParts1[1]);
        mDelayedPart12.update(delayParts1[2]);

     }
    void deconfigure()
    {
        delete mpSolver;
    }
};
#endif // AEROTURBYFILTER_HPP_INCLUDED
