set(local_fmi4c_dir ${CMAKE_CURRENT_LIST_DIR}/fmi4c)

if (EXISTS ${local_fmi4c_dir})
  find_package(fmi4c CONFIG PATHS ${local_fmi4c_dir} NO_DEFAULT_PATH)
  if (fmi4c_FOUND)
    message(STATUS "Building with Fmi4c support")
    target_compile_definitions(fmi4c::fmi4c INTERFACE USEFMI4C)
    install(DIRECTORY ${local_fmi4c_dir} DESTINATION dependencies)
  else()
    message(WARNING "Fmi4c configuration packet not found in ${local_fmi4c_dir}")
  endif()
else()
  message(WARNING "Building without Fmi4c support")
endif()
