set(local_hdf5_dir ${CMAKE_CURRENT_LIST_DIR}/hdf5)
find_package(Hdf5 CONFIG COMPONENTS C CXX PATHS ${local_hdf5_dir}/cmake ${local_hdf5_dir}/share/cmake)
if (Hdf5_FOUND)
  message(STATUS "Building with HDF5 support")
  target_compile_definitions(hdf5::hdf5-shared INTERFACE USEHDF5)
else()
  message(WARNING "Building without HDF5 support")
endif()

if (EXISTS ${local_hdf5_dir})
  if(WIN32)
    file(GLOB lib_files ${local_hdf5_dir}/bin/${CMAKE_SHARED_LIBRARY_PREFIX}hdf5${CMAKE_SHARED_LIBRARY_SUFFIX}
                        ${local_hdf5_dir}/bin/${CMAKE_SHARED_LIBRARY_PREFIX}hdf5_cpp${CMAKE_SHARED_LIBRARY_SUFFIX})
    install(FILES ${lib_files} DESTINATION bin)
  else()
    file(GLOB lib_files ${local_hdf5_dir}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}hdf5${CMAKE_SHARED_LIBRARY_SUFFIX}*
                        ${local_hdf5_dir}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}hdf5_cpp${CMAKE_SHARED_LIBRARY_SUFFIX}*)
    install(FILES ${lib_files} DESTINATION lib)
  endif()
endif()
