#!/bin/bash
./setupAsio.sh
./setupDiscount.sh
./setupFmi4c.sh
./setupFMILibrary.sh
./setupQwt.sh
./setupMsgpack.sh
./setupZeroMQ.sh
./setupKatex.sh
./setupTclap.sh
./setupHDF5.sh
./setupXerces.sh
./setupLibzip.sh
./setupDCPLib.sh
