set(local_ssp4c_dir ${CMAKE_CURRENT_LIST_DIR}/ssp4c)

if (EXISTS ${local_ssp4c_dir})
  find_package(ssp4c CONFIG PATHS ${local_ssp4c_dir} NO_DEFAULT_PATH)
  if (ssp4c_FOUND)
    message(STATUS "Building with ssp4c support")
    target_compile_definitions(ssp4c::ssp4c INTERFACE USESSP4C)
    install(DIRECTORY ${local_ssp4c_dir} DESTINATION dependencies)
  else()
    message(WARNING "Ssp4c configuration packet not found in ${local_ssp4c_dir}")
  endif()
else()
  message(WARNING "Building without ssp4c support")
endif()
