if (NOT TARGET xercesc)
    set(local_xerces_dir ${CMAKE_CURRENT_LIST_DIR}/xerces)
    find_package(XercesC CONFIG PATHS ${local_xerces_dir} NO_DEFAULT_PATH)

    if (XercesC_FOUND)
        message(STATUS "Found local xerces")
    else()
        message(STATUS "Looking for xerces in system")
        find_package(xercesc CONFIG) # Search in system
        if (xercesc_FOUND)
            message(STATUS "Found xerces in system")
        else()
            message(WARNING "Could not find xerces")
        endif()
    endif()
endif()
