#ifndef SIGNALFFBANDIN_HPP_INCLUDED
#define SIGNALFFBANDIN_HPP_INCLUDED

#include <iostream>
#include "ComponentEssentials.h"
#include "ComponentUtilities.h"
#include "math.h"

//!
//! @file SignalFFBandIn.hpp
//! @author Petter Krus <petter.krus@liu.se>
//! @date Fri 24 Aug 2012 10:31:18
//! @brief FFBD AND(in)
//! @ingroup SignalComponents
//!
//This component is generated by COMPGEN for HOPSAN-NG simulation 
//from 
/*{, C:, Documents and Settings, petkr14, My Documents, \
CompgenNG}/FFBDcomponentsNG.nb*/

using namespace hopsan;

class SignalFFBandIn : public ComponentSignal
{
private:
     double min0;
     Port *mpPin0;
     Port *mpPstate;
     Port *mpPout0;
     Port *mpPout1;
     int mNstep;
     //inputVariables
     double in0;
     //outputVariables
     double state;
     double out0;
     double out1;
     //Expressions variables
     double oldState;
     double oldIn0;
     double oldOut0;
     //Delay declarations
     //inputVariables pointers
     double *mpND_in0;
     //outputVariables pointers
     double *mpND_state;
     double *mpND_out0;
     double *mpND_out1;
     EquationSystemSolver *mpSolver;

public:
     static Component *Creator()
     {
        return new SignalFFBandIn();
     }

     void configure()
     {
        const double in0 = 0.;

        mNstep=9;
        min0 = in0;

        //Add ports to the component

        //Add inputVariables ports to the component
        mpPin0=addReadPort("Pin0","NodeSignal", Port::NotRequired);

        //Add outputVariables ports to the component
        mpPstate=addWritePort("Pstate","NodeSignal", Port::NotRequired);
        mpPout0=addWritePort("Pout0","NodeSignal", Port::NotRequired);
        mpPout1=addWritePort("Pout1","NodeSignal", Port::NotRequired);

        //Register changable parameters to the HOPSAN++ core
        registerParameter("in0", "Input 0", "", min0);
     }

    void initialize()
     {
        //Read port variable pointers from nodes
        //Read inputVariables pointers from nodes
        mpND_in0=getSafeNodeDataPtr(mpPin0, NodeSignal::VALUE,min0);
        //Read outputVariable pointers from nodes
        mpND_state=getSafeNodeDataPtr(mpPstate, NodeSignal::VALUE);
        mpND_out0=getSafeNodeDataPtr(mpPout0, NodeSignal::VALUE);
        mpND_out1=getSafeNodeDataPtr(mpPout1, NodeSignal::VALUE);

        //Read variables from nodes

        //Read inputVariables from nodes
        in0 = (*mpND_in0);

        //Read outputVariables from nodes
        state = mpPstate->getStartValue(NodeSignal::VALUE);
        out0 = mpPout0->getStartValue(NodeSignal::VALUE);
        out1 = mpPout1->getStartValue(NodeSignal::VALUE);

        //InitialExpressions
        oldState = state;
        oldIn0 = in0;
        oldOut0 = out0;


        //Initialize delays

     }
    void simulateOneTimestep()
     {
        //Read variables from nodes

        //Read inputVariables from nodes
        in0 = (*mpND_in0);

        //LocalExpressions

          //Expressions
          state = onPositive(-0.5 + 2*onPositive(-0.5 + in0 - oldIn0) - \
onPositive(-0.5 + oldOut0) + onPositive(-0.5 + oldState));
          out0 = state;
          out1 = state;
          oldState = state;
          oldIn0 = in0;
          oldOut0 = out0;

        //Calculate the delayed parts


        //Write new values to nodes
        //outputVariables
        (*mpND_state)=state;
        (*mpND_out0)=out0;
        (*mpND_out1)=out1;

        //Update the delayed variabels

     }
};
#endif // SIGNALFFBANDIN_HPP_INCLUDED
