#ifndef HOPSANDEFAULTOPTIMIZATIONTESTFUNCTIONCOMPONENTS_H
#define HOPSANDEFAULTOPTIMIZATIONTESTFUNCTIONCOMPONENTS_H

#include "OptimizationTestFunction2D.hpp"
#include "OptimizationTestFunction5D.hpp"
#include "OptimizationTestFunction6D.hpp"

#endif // HOPSANDEFAULTBENCHMARKINGCOMPONENTS_H
