#ifndef AEROAIRCRAFT6DOFS_HPP_INCLUDED
#define AEROAIRCRAFT6DOFS_HPP_INCLUDED

#include <iostream>
#include "ComponentEssentials.h"
#include "ComponentUtilities.h"
#include "math.h"

//!
//! @file AeroAircraft6DOFS.hpp
//! @author Petter Krus <petter.krus@liu.se>
//! @date Tue 11 Sep 2012 09:35:52
//! @brief Flight dynamics model of aircraft
//! @ingroup AeroComponents
//!
//This component is generated by COMPGEN for HOPSAN-NG simulation 
//from 
/*{, C:, Documents and Settings, petkr14, My Documents, \
CompgenNG}/AeroAircraft6DOFS.nb*/

using namespace hopsan;

class AeroAircraft6DOFS : public ComponentC
{
private:
     double mafin;
     double man1;
     double man2;
     double map1;
     double map2;
     double mAR1;
     double mAR2;
     double mARfin;
     double mCd01;
     double mCd02;
     double mCd0b;
     double mCd0fin;
     double mCLalpha1;
     double mCLalpha2;
     double mCLalphabh;
     double mCLalphabv;
     double mCLalphafin;
     double mCLde1;
     double mCLde2;
     double mCLde12;
     double mCdide1;
     double mCdide12;
     double mCdide112;
     double mde10;
     double mde120;
     double mCm01;
     double mCmfs1;
     double mCmde1;
     double mCmde12;
     double mCLdefin;
     double mdah1;
     double mdah2;
     double me1;
     double me2;
     double mefin;
     double mawfin;
     double mawn1;
     double mawn2;
     double mawp1;
     double mawp2;
     double mgamma1;
     double mgamma2;
     double mhthrust0;
     double mia1;
     double mia2;
     double mIx0;
     double mIxz0;
     double mIy0;
     double mIz0;
     double mlambda1;
     double mlambda2;
     double mlambdafin;
     double mlc10;
     double mlc20;
     double mlc120;
     double mlcfin0;
     double mMe;
     double mrc10;
     double mrc20;
     double mrcfin0;
     double mS1;
     double mS20;
     double mSbh0;
     double mSbv0;
     double mSfin0;
     double mxbach0;
     double mxbacv0;
     double mxbcge0;
     double mxcargo0;
     double mxfuel0;
     double mxw10;
     double mxw20;
     double mxwfin0;
     double myeng0;
     double mg0;
     double mkground;
     double mcground;
     double mthrustl;
     double mthrustr;
     double mdezthrust;
     double mMfuel;
     double mMcargo;
     double mrho;
     double mvturbx;
     double mvturby;
     double mvturbz;
     double mwturbx;
     double mwturby;
     double mwturbz;
     Port *mpPal1;
     Port *mpPar1;
     Port *mpPal12;
     Port *mpPar12;
     Port *mpPal2;
     Port *mpPar2;
     Port *mpPfin;
     Port *mpPthrustl;
     Port *mpPthrustr;
     Port *mpPdezthrust;
     Port *mpPMfuel;
     Port *mpPMcargo;
     Port *mpPrho;
     Port *mpPvturbx;
     Port *mpPvturby;
     Port *mpPvturbz;
     Port *mpPwturbx;
     Port *mpPwturby;
     Port *mpPwturbz;
     Port *mpPxcg;
     Port *mpPycg;
     Port *mpPzcg;
     Port *mpPvx;
     Port *mpPvy;
     Port *mpPvz;
     Port *mpPPsi;
     Port *mpPThetao;
     Port *mpPPhi;
     Port *mpPUb;
     Port *mpPVb;
     Port *mpPWb;
     Port *mpPPb;
     Port *mpPQb;
     Port *mpPRb;
     Port *mpPq0;
     Port *mpPq1;
     Port *mpPq2;
     Port *mpPq3;
     Port *mpPAlphaAttack;
     Port *mpPBetaSlip;
     Port *mpPaltitude;
     Port *mpPgfx;
     Port *mpPgfy;
     Port *mpPgfz;
     Port *mpPCL1;
     Port *mpPCd1;
     Port *mpPFax;
     Port *mpPFaz;
     double delayParts1[9];
     double delayParts2[9];
     double delayParts3[9];
     double delayParts4[9];
     double delayParts5[9];
     double delayParts6[9];
     double delayParts7[9];
     double delayParts8[9];
     double delayParts9[9];
     double delayParts10[9];
     double delayParts11[9];
     double delayParts12[9];
     double delayParts13[9];
     Matrix jacobianMatrix;
     Vec systemEquations;
     Matrix delayedPart;
     int i;
     int iter;
     int mNoiter;
     double jsyseqnweight[4];
     int order[13];
     int mNstep;
     //Port Pal1 variable
     double toral1;
     double thetaal1;
     double wal1;
     double cal1;
     double Zcal1;
     double eqInertiaal1;
     //Port Par1 variable
     double torar1;
     double thetaar1;
     double war1;
     double car1;
     double Zcar1;
     double eqInertiaar1;
     //Port Pal12 variable
     double toral12;
     double thetaal12;
     double wal12;
     double cal12;
     double Zcal12;
     double eqInertiaal12;
     //Port Par12 variable
     double torar12;
     double thetaar12;
     double war12;
     double car12;
     double Zcar12;
     double eqInertiaar12;
     //Port Pal2 variable
     double toral2;
     double thetaal2;
     double wal2;
     double cal2;
     double Zcal2;
     double eqInertiaal2;
     //Port Par2 variable
     double torar2;
     double thetaar2;
     double war2;
     double car2;
     double Zcar2;
     double eqInertiaar2;
     //Port Pfin variable
     double torfin;
     double thetafin;
     double wfin;
     double cfin;
     double Zcfin;
     double eqInertiafin;
     //inputVariables
     double thrustl;
     double thrustr;
     double dezthrust;
     double Mfuel;
     double Mcargo;
     double rho;
     double vturbx;
     double vturby;
     double vturbz;
     double wturbx;
     double wturby;
     double wturbz;
     //outputVariables
     double xcg;
     double ycg;
     double zcg;
     double vx;
     double vy;
     double vz;
     double Psi;
     double Thetao;
     double Phi;
     double Ub;
     double Vb;
     double Wb;
     double Pb;
     double Qb;
     double Rb;
     double q0;
     double q1;
     double q2;
     double q3;
     double AlphaAttack;
     double BetaSlip;
     double altitude;
     double gfx;
     double gfy;
     double gfz;
     double CL1;
     double Cd1;
     double Fax;
     double Faz;
     //LocalExpressions variables
     double hthrust;
     double Ix;
     double Ixz;
     double Iy;
     double Iz;
     double lc1;
     double lc2;
     double lc12;
     double lcfin;
     double rc1;
     double rc2;
     double rcfin;
     double S2;
     double Sbh;
     double Sbv;
     double Sfin;
     double xbach;
     double xbacv;
     double xbcge;
     double xcargo;
     double xfuel;
     double xw1;
     double xw2;
     double xwfin;
     double yeng;
     double v;
     double Alpha;
     double qpress;
     double Beta;
     double mass;
     double xbcg;
     double Dragl1;
     double Dragr1;
     double Liftl1;
     double Liftr1;
     double Dragl2;
     double Dragr2;
     double Liftl2;
     double Liftr2;
     double Liftb;
     double Dragb;
     double Cfin;
     double Dragfin;
     double Mdvtheta;
     double Mdvpsi;
     double Fx;
     double Fy;
     double Fz;
     double Lb;
     double Mb;
     double Nb;
     //Expressions variables
     //Port Pal1 pointer
     double *mpND_toral1;
     double *mpND_thetaal1;
     double *mpND_wal1;
     double *mpND_cal1;
     double *mpND_Zcal1;
     double *mpND_eqInertiaal1;
     //Port Par1 pointer
     double *mpND_torar1;
     double *mpND_thetaar1;
     double *mpND_war1;
     double *mpND_car1;
     double *mpND_Zcar1;
     double *mpND_eqInertiaar1;
     //Port Pal12 pointer
     double *mpND_toral12;
     double *mpND_thetaal12;
     double *mpND_wal12;
     double *mpND_cal12;
     double *mpND_Zcal12;
     double *mpND_eqInertiaal12;
     //Port Par12 pointer
     double *mpND_torar12;
     double *mpND_thetaar12;
     double *mpND_war12;
     double *mpND_car12;
     double *mpND_Zcar12;
     double *mpND_eqInertiaar12;
     //Port Pal2 pointer
     double *mpND_toral2;
     double *mpND_thetaal2;
     double *mpND_wal2;
     double *mpND_cal2;
     double *mpND_Zcal2;
     double *mpND_eqInertiaal2;
     //Port Par2 pointer
     double *mpND_torar2;
     double *mpND_thetaar2;
     double *mpND_war2;
     double *mpND_car2;
     double *mpND_Zcar2;
     double *mpND_eqInertiaar2;
     //Port Pfin pointer
     double *mpND_torfin;
     double *mpND_thetafin;
     double *mpND_wfin;
     double *mpND_cfin;
     double *mpND_Zcfin;
     double *mpND_eqInertiafin;
     //Delay declarations
     //inputVariables pointers
     double *mpND_thrustl;
     double *mpND_thrustr;
     double *mpND_dezthrust;
     double *mpND_Mfuel;
     double *mpND_Mcargo;
     double *mpND_rho;
     double *mpND_vturbx;
     double *mpND_vturby;
     double *mpND_vturbz;
     double *mpND_wturbx;
     double *mpND_wturby;
     double *mpND_wturbz;
     //outputVariables pointers
     double *mpND_xcg;
     double *mpND_ycg;
     double *mpND_zcg;
     double *mpND_vx;
     double *mpND_vy;
     double *mpND_vz;
     double *mpND_Psi;
     double *mpND_Thetao;
     double *mpND_Phi;
     double *mpND_Ub;
     double *mpND_Vb;
     double *mpND_Wb;
     double *mpND_Pb;
     double *mpND_Qb;
     double *mpND_Rb;
     double *mpND_q0;
     double *mpND_q1;
     double *mpND_q2;
     double *mpND_q3;
     double *mpND_AlphaAttack;
     double *mpND_BetaSlip;
     double *mpND_altitude;
     double *mpND_gfx;
     double *mpND_gfy;
     double *mpND_gfz;
     double *mpND_CL1;
     double *mpND_Cd1;
     double *mpND_Fax;
     double *mpND_Faz;
     Delay mDelayedPart10;
     Delay mDelayedPart11;
     Delay mDelayedPart20;
     Delay mDelayedPart21;
     Delay mDelayedPart30;
     Delay mDelayedPart31;
     Delay mDelayedPart40;
     Delay mDelayedPart41;
     Delay mDelayedPart50;
     Delay mDelayedPart51;
     Delay mDelayedPart60;
     Delay mDelayedPart61;
     Delay mDelayedPart70;
     Delay mDelayedPart71;
     Delay mDelayedPart80;
     Delay mDelayedPart81;
     Delay mDelayedPart90;
     Delay mDelayedPart91;
     Delay mDelayedPart100;
     Delay mDelayedPart101;
     Delay mDelayedPart110;
     Delay mDelayedPart111;
     Delay mDelayedPart120;
     Delay mDelayedPart121;
     Delay mDelayedPart130;
     Delay mDelayedPart131;
     EquationSystemSolver *mpSolver;

public:
     static Component *Creator()
     {
        return new AeroAircraft6DOFS();
     }

     void configure()
     {
        const double afin = 0.3;
        const double an1 = 0.6;
        const double an2 = 0.6;
        const double ap1 = 0.9;
        const double ap2 = 0.7;
        const double AR1 = 2.24;
        const double AR2 = 2.2;
        const double ARfin = 0.58;
        const double Cd01 = 0.0045;
        const double Cd02 = 0.0045;
        const double Cd0b = 0.004;
        const double Cd0fin = 0.0045;
        const double CLalpha1 = 2.1;
        const double CLalpha2 = 2.2;
        const double CLalphabh = 2.;
        const double CLalphabv = 2.;
        const double CLalphafin = 0.8;
        const double CLde1 = 0.1;
        const double CLde2 = 0.515;
        const double CLde12 = 0.2;
        const double Cdide1 = 0.;
        const double Cdide12 = 0.;
        const double Cdide112 = 0.;
        const double de10 = 0.01;
        const double de120 = 0.01;
        const double Cm01 = -0.1;
        const double Cmfs1 = -0.5;
        const double Cmde1 = 0.02;
        const double Cmde12 = 0.1;
        const double CLdefin = 0.0827084;
        const double dah1 = 1.;
        const double dah2 = 0.6;
        const double e1 = 0.95;
        const double e2 = 0.95;
        const double efin = 0.95;
        const double awfin = 0.2;
        const double awn1 = 0.2;
        const double awn2 = 0.2;
        const double awp1 = 0.2;
        const double awp2 = 0.2;
        const double gamma1 = -0.0872665;
        const double gamma2 = -0.0872665;
        const double hthrust0 = 0.;
        const double ia1 = 0.;
        const double ia2 = 0.02;
        const double Ix0 = 0.0022;
        const double Ixz0 = 0.001;
        const double Iy0 = 0.06;
        const double Iz0 = 0.08;
        const double lambda1 = 0.436332;
        const double lambda2 = 0.436332;
        const double lambdafin = 0.785398;
        const double lc10 = 0.005;
        const double lc20 = 0.005;
        const double lc120 = 0.005;
        const double lcfin0 = 0.005;
        const double Me = 5000.;
        const double rc10 = 0.25;
        const double rc20 = 0.15;
        const double rcfin0 = 0.1;
        const double S1 = 40.;
        const double S20 = 0.5;
        const double Sbh0 = 0.2;
        const double Sbv0 = 0.2;
        const double Sfin0 = 0.17;
        const double xbach0 = 2;
        const double xbacv0 = 2;
        const double xbcge0 = 1.4;
        const double xcargo0 = 1.4;
        const double xfuel0 = 1.4;
        const double xw10 = 1.55;
        const double xw20 = 2.6;
        const double xwfin0 = 2.6;
        const double yeng0 = 0.;
        const double g0 = 9.81;
        const double kground = 10000.;
        const double cground = 1000.;
        const double thrustl = 0.;
        const double thrustr = 0.;
        const double dezthrust = 0.;
        const double Mfuel = 0.;
        const double Mcargo = 0.;
        const double rho = 1.25;
        const double vturbx = 0.;
        const double vturby = 0.;
        const double vturbz = 0.;
        const double wturbx = 0.;
        const double wturby = 0.;
        const double wturbz = 0.;

        mNstep=9;
        jacobianMatrix.create(13,13);
        systemEquations.create(13);
        delayedPart.create(14,6);
        mNoiter=2;
        jsyseqnweight[0]=1;
        jsyseqnweight[1]=0.67;
        jsyseqnweight[2]=0.5;
        jsyseqnweight[3]=0.5;

        mafin = afin;
        man1 = an1;
        man2 = an2;
        map1 = ap1;
        map2 = ap2;
        mAR1 = AR1;
        mAR2 = AR2;
        mARfin = ARfin;
        mCd01 = Cd01;
        mCd02 = Cd02;
        mCd0b = Cd0b;
        mCd0fin = Cd0fin;
        mCLalpha1 = CLalpha1;
        mCLalpha2 = CLalpha2;
        mCLalphabh = CLalphabh;
        mCLalphabv = CLalphabv;
        mCLalphafin = CLalphafin;
        mCLde1 = CLde1;
        mCLde2 = CLde2;
        mCLde12 = CLde12;
        mCdide1 = Cdide1;
        mCdide12 = Cdide12;
        mCdide112 = Cdide112;
        mde10 = de10;
        mde120 = de120;
        mCm01 = Cm01;
        mCmfs1 = Cmfs1;
        mCmde1 = Cmde1;
        mCmde12 = Cmde12;
        mCLdefin = CLdefin;
        mdah1 = dah1;
        mdah2 = dah2;
        me1 = e1;
        me2 = e2;
        mefin = efin;
        mawfin = awfin;
        mawn1 = awn1;
        mawn2 = awn2;
        mawp1 = awp1;
        mawp2 = awp2;
        mgamma1 = gamma1;
        mgamma2 = gamma2;
        mhthrust0 = hthrust0;
        mia1 = ia1;
        mia2 = ia2;
        mIx0 = Ix0;
        mIxz0 = Ixz0;
        mIy0 = Iy0;
        mIz0 = Iz0;
        mlambda1 = lambda1;
        mlambda2 = lambda2;
        mlambdafin = lambdafin;
        mlc10 = lc10;
        mlc20 = lc20;
        mlc120 = lc120;
        mlcfin0 = lcfin0;
        mMe = Me;
        mrc10 = rc10;
        mrc20 = rc20;
        mrcfin0 = rcfin0;
        mS1 = S1;
        mS20 = S20;
        mSbh0 = Sbh0;
        mSbv0 = Sbv0;
        mSfin0 = Sfin0;
        mxbach0 = xbach0;
        mxbacv0 = xbacv0;
        mxbcge0 = xbcge0;
        mxcargo0 = xcargo0;
        mxfuel0 = xfuel0;
        mxw10 = xw10;
        mxw20 = xw20;
        mxwfin0 = xwfin0;
        myeng0 = yeng0;
        mg0 = g0;
        mkground = kground;
        mcground = cground;
        mthrustl = thrustl;
        mthrustr = thrustr;
        mdezthrust = dezthrust;
        mMfuel = Mfuel;
        mMcargo = Mcargo;
        mrho = rho;
        mvturbx = vturbx;
        mvturby = vturby;
        mvturbz = vturbz;
        mwturbx = wturbx;
        mwturby = wturby;
        mwturbz = wturbz;

        //Add ports to the component
        mpPal1=addPowerPort("Pal1","NodeMechanicRotational");
        mpPar1=addPowerPort("Par1","NodeMechanicRotational");
        mpPal12=addPowerPort("Pal12","NodeMechanicRotational");
        mpPar12=addPowerPort("Par12","NodeMechanicRotational");
        mpPal2=addPowerPort("Pal2","NodeMechanicRotational");
        mpPar2=addPowerPort("Par2","NodeMechanicRotational");
        mpPfin=addPowerPort("Pfin","NodeMechanicRotational");

        //Add inputVariables ports to the component
        mpPthrustl=addReadPort("Pthrustl","NodeSignal", Port::NOTREQUIRED);
        mpPthrustr=addReadPort("Pthrustr","NodeSignal", Port::NOTREQUIRED);
        mpPdezthrust=addReadPort("Pdezthrust","NodeSignal", \
Port::NOTREQUIRED);
        mpPMfuel=addReadPort("PMfuel","NodeSignal", Port::NOTREQUIRED);
        mpPMcargo=addReadPort("PMcargo","NodeSignal", Port::NOTREQUIRED);
        mpPrho=addReadPort("Prho","NodeSignal", Port::NOTREQUIRED);
        mpPvturbx=addReadPort("Pvturbx","NodeSignal", Port::NOTREQUIRED);
        mpPvturby=addReadPort("Pvturby","NodeSignal", Port::NOTREQUIRED);
        mpPvturbz=addReadPort("Pvturbz","NodeSignal", Port::NOTREQUIRED);
        mpPwturbx=addReadPort("Pwturbx","NodeSignal", Port::NOTREQUIRED);
        mpPwturby=addReadPort("Pwturby","NodeSignal", Port::NOTREQUIRED);
        mpPwturbz=addReadPort("Pwturbz","NodeSignal", Port::NOTREQUIRED);

        //Add outputVariables ports to the component
        mpPxcg=addWritePort("Pxcg","NodeSignal", Port::NOTREQUIRED);
        mpPycg=addWritePort("Pycg","NodeSignal", Port::NOTREQUIRED);
        mpPzcg=addWritePort("Pzcg","NodeSignal", Port::NOTREQUIRED);
        mpPvx=addWritePort("Pvx","NodeSignal", Port::NOTREQUIRED);
        mpPvy=addWritePort("Pvy","NodeSignal", Port::NOTREQUIRED);
        mpPvz=addWritePort("Pvz","NodeSignal", Port::NOTREQUIRED);
        mpPPsi=addWritePort("PPsi","NodeSignal", Port::NOTREQUIRED);
        mpPThetao=addWritePort("PThetao","NodeSignal", Port::NOTREQUIRED);
        mpPPhi=addWritePort("PPhi","NodeSignal", Port::NOTREQUIRED);
        mpPUb=addWritePort("PUb","NodeSignal", Port::NOTREQUIRED);
        mpPVb=addWritePort("PVb","NodeSignal", Port::NOTREQUIRED);
        mpPWb=addWritePort("PWb","NodeSignal", Port::NOTREQUIRED);
        mpPPb=addWritePort("PPb","NodeSignal", Port::NOTREQUIRED);
        mpPQb=addWritePort("PQb","NodeSignal", Port::NOTREQUIRED);
        mpPRb=addWritePort("PRb","NodeSignal", Port::NOTREQUIRED);
        mpPq0=addWritePort("Pq0","NodeSignal", Port::NOTREQUIRED);
        mpPq1=addWritePort("Pq1","NodeSignal", Port::NOTREQUIRED);
        mpPq2=addWritePort("Pq2","NodeSignal", Port::NOTREQUIRED);
        mpPq3=addWritePort("Pq3","NodeSignal", Port::NOTREQUIRED);
        mpPAlphaAttack=addWritePort("PAlphaAttack","NodeSignal", \
Port::NOTREQUIRED);
        mpPBetaSlip=addWritePort("PBetaSlip","NodeSignal", \
Port::NOTREQUIRED);
        mpPaltitude=addWritePort("Paltitude","NodeSignal", \
Port::NOTREQUIRED);
        mpPgfx=addWritePort("Pgfx","NodeSignal", Port::NOTREQUIRED);
        mpPgfy=addWritePort("Pgfy","NodeSignal", Port::NOTREQUIRED);
        mpPgfz=addWritePort("Pgfz","NodeSignal", Port::NOTREQUIRED);
        mpPCL1=addWritePort("PCL1","NodeSignal", Port::NOTREQUIRED);
        mpPCd1=addWritePort("PCd1","NodeSignal", Port::NOTREQUIRED);
        mpPFax=addWritePort("PFax","NodeSignal", Port::NOTREQUIRED);
        mpPFaz=addWritePort("PFaz","NodeSignal", Port::NOTREQUIRED);

        //Register changable parameters to the HOPSAN++ core
        registerParameter("afin", "break angle 1", "rad", mafin);
        registerParameter("an1", "Neg. break angle 1", "rad", man1);
        registerParameter("an2", "Neg. break angle 2", "rad", man2);
        registerParameter("ap1", "Pos. break angle 1", "rad", map1);
        registerParameter("ap2", "Pos. break angle 2", "rad", map2);
        registerParameter("AR1", "Aspect ratio 1", "", mAR1);
        registerParameter("AR2", "Aspect rati 2o", "", mAR2);
        registerParameter("ARfin", "Aspect ratio fin", "", mARfin);
        registerParameter("Cd01", "Drag coef. 1", "", mCd01);
        registerParameter("Cd02", "Drag coef. 2", "", mCd02);
        registerParameter("Cd0b", "Drag coef. body", "", mCd0b);
        registerParameter("Cd0fin", "Drag coef. fin", "", mCd0fin);
        registerParameter("CLalpha1", "L. slope coef. 1", "", mCLalpha1);
        registerParameter("CLalpha2", "L. slope coef. 2", "", mCLalpha2);
        registerParameter("CLalphabh", "L. slope c. body h", "", mCLalphabh);
        registerParameter("CLalphabv", "L. slope c. bodyv", "", mCLalphabv);
        registerParameter("CLalphafin", "L. sl. c. fin", "", mCLalphafin);
        registerParameter("CLde1", "Ctrl surface coef 1", "", mCLde1);
        registerParameter("CLde2", "Ctrl surface coef 1", "", mCLde2);
        registerParameter("CLde12", "Flap rudder coef 1", "", mCLde12);
        registerParameter("Cdide1", "Flap rudder drag coef 1", "", mCdide1);
        registerParameter("Cdide12", "Flap rudder drag coef 1", "", \
mCdide12);
        registerParameter("Cdide112", "Flap rudder cross drag coef 1", "", \
mCdide112);
        registerParameter("de10", "rudder min drag angle 1", "", mde10);
        registerParameter("de120", "Flap min drag angle 1", "", mde120);
        registerParameter("Cm01", "Mom coeff. wing 1", "", mCm01);
        registerParameter("Cmfs1", "Mom coeff.1, fully separated", "", \
mCmfs1);
        registerParameter("Cmde1", "Mom slop coeff 1", "", mCmde1);
        registerParameter("Cmde12", "Flap Mom slop coeff 1", "", mCmde12);
        registerParameter("CLdefin", "Rudder coef 1", "", mCLdefin);
        registerParameter("dah1", "down wash effect on 1", "", mdah1);
        registerParameter("dah2", "down wash effect on 2", "", mdah2);
        registerParameter("e1", "Osw. effic. factor 1", "", me1);
        registerParameter("e2", "Osw. effic. factor 1", "", me2);
        registerParameter("efin", "Osw. eff. f. fin", "", mefin);
        registerParameter("awfin", "CL exponent fin", "", mawfin);
        registerParameter("awn1", "CL exponent neg. 1", "", mawn1);
        registerParameter("awn2", "CL exponent neg. 2", "", mawn2);
        registerParameter("awp1", "CL exponent pos 1", "", mawp1);
        registerParameter("awp2", "CL exponent neg 1", "", mawp2);
        registerParameter("gamma1", "dehidral", "rad", mgamma1);
        registerParameter("gamma2", "dehidral", "rad", mgamma2);
        registerParameter("hthrust0", "engine vert. pos", "", mhthrust0);
        registerParameter("ia1", "incidence angle 1", "rad", mia1);
        registerParameter("ia2", "incidence angle 1", " rad", mia2);
        registerParameter("Ix0", "Norm. Inertia moment Ix/(Me S1)", " ", \
mIx0);
        registerParameter("Ixz0", "Norm. Inertia moment", " ", mIxz0);
        registerParameter("Iy0", "Norm. Inertia moment", " ", mIy0);
        registerParameter("Iz0", "Inertia moment", " ", mIz0);
        registerParameter("lambda1", "sweep 1", "rad", mlambda1);
        registerParameter("lambda2", "sweep 2", "rad", mlambda2);
        registerParameter("lambdafin", "sweep fin", "rad", mlambdafin);
        registerParameter("lc10", "norm. ctrl surf. 1 ac fr hinge \
lc1/sqrt(AR1 S1)", "", mlc10);
        registerParameter("lc20", "norm. ctrl surf. 2 ac fr hinge \
lc1/sqrt(AR1 S1)", "", mlc20);
        registerParameter("lc120", "norm. flap 1 ac fr hinge", "", mlc120);
        registerParameter("lcfin0", "ctrl s. fin ac fr hinge", "", mlcfin0);
        registerParameter("Me", "Empty weight", "kg", mMe);
        registerParameter("rc10", "norm. ctrl surface 1 mom. arm", "", \
mrc10);
        registerParameter("rc20", "norm. ctrl surface 1 mom. arm", "", \
mrc20);
        registerParameter("rcfin0", "norm. ctrl surf. fin mom. arm", "", \
mrcfin0);
        registerParameter("S1", "wing area 1", "m2", mS1);
        registerParameter("S20", "norm. wing area 2", "", mS20);
        registerParameter("Sbh0", "norm. hor. proj. area", "", mSbh0);
        registerParameter("Sbv0", "norm.body vert. proj. area", "", mSbv0);
        registerParameter("Sfin0", "norm. fin area", "", mSfin0);
        registerParameter("xbach0", "norm. body ac. hor.", "", mxbach0);
        registerParameter("xbacv0", "norm. body ac vert.", " ", mxbacv0);
        registerParameter("xbcge0", "norm. body cg", " ", mxbcge0);
        registerParameter("xcargo0", "norm. cargo pos.", " ", mxcargo0);
        registerParameter("xfuel0", "", " ", mxfuel0);
        registerParameter("xw10", "norm. wing1  position", " ", mxw10);
        registerParameter("xw20", "norm. wing 2 position", " ", mxw20);
        registerParameter("xwfin0", "norm. fin position", "", mxwfin0);
        registerParameter("yeng0", "engines off. from center", "", myeng0);
        registerParameter("g0", "Gravity acceleration", "m/s^2", mg0);
        registerParameter("kground", "Ground stiffness (for limitiation)", \
"N/m", mkground);
        registerParameter("cground", "Ground damping (for limitiation)", \
"Ns/m", mcground);
        registerParameter("thrustl", "Engine thrust", "N", mthrustl);
        registerParameter("thrustr", "Engine thrust", "N", mthrustr);
        registerParameter("dezthrust", "Thrust angle", "rad", mdezthrust);
        registerParameter("Mfuel", "Fuel weight", "kg", mMfuel);
        registerParameter("Mcargo", "Cargo weight", "kg", mMcargo);
        registerParameter("rho", "Air density", "kg/m3", mrho);
        registerParameter("vturbx", "air turbulence x", "m/s", mvturbx);
        registerParameter("vturby", "air turbulence y", "m/s", mvturby);
        registerParameter("vturbz", "air turbulence z", "m/s", mvturbz);
        registerParameter("wturbx", "air turbulence x", "rad/s", mwturbx);
        registerParameter("wturby", "air turbulence y", "rad/s", mwturby);
        registerParameter("wturbz", "air turbulence z", "rad/s", mwturbz);
        mpSolver = new EquationSystemSolver(this,13);
     }

    void initialize()
     {
        //Read port variable pointers from nodes
        //Port Pal1
        mpND_toral1=getSafeNodeDataPtr(mpPal1, \
NodeMechanicRotational::TORQUE);
        mpND_thetaal1=getSafeNodeDataPtr(mpPal1, \
NodeMechanicRotational::ANGLE);
        mpND_wal1=getSafeNodeDataPtr(mpPal1, \
NodeMechanicRotational::ANGULARVELOCITY);
        mpND_cal1=getSafeNodeDataPtr(mpPal1, \
NodeMechanicRotational::WAVEVARIABLE);
        mpND_Zcal1=getSafeNodeDataPtr(mpPal1, \
NodeMechanicRotational::CHARIMP);
        mpND_eqInertiaal1=getSafeNodeDataPtr(mpPal1, \
NodeMechanicRotational::EQINERTIA);
        //Port Par1
        mpND_torar1=getSafeNodeDataPtr(mpPar1, \
NodeMechanicRotational::TORQUE);
        mpND_thetaar1=getSafeNodeDataPtr(mpPar1, \
NodeMechanicRotational::ANGLE);
        mpND_war1=getSafeNodeDataPtr(mpPar1, \
NodeMechanicRotational::ANGULARVELOCITY);
        mpND_car1=getSafeNodeDataPtr(mpPar1, \
NodeMechanicRotational::WAVEVARIABLE);
        mpND_Zcar1=getSafeNodeDataPtr(mpPar1, \
NodeMechanicRotational::CHARIMP);
        mpND_eqInertiaar1=getSafeNodeDataPtr(mpPar1, \
NodeMechanicRotational::EQINERTIA);
        //Port Pal12
        mpND_toral12=getSafeNodeDataPtr(mpPal12, \
NodeMechanicRotational::TORQUE);
        mpND_thetaal12=getSafeNodeDataPtr(mpPal12, \
NodeMechanicRotational::ANGLE);
        mpND_wal12=getSafeNodeDataPtr(mpPal12, \
NodeMechanicRotational::ANGULARVELOCITY);
        mpND_cal12=getSafeNodeDataPtr(mpPal12, \
NodeMechanicRotational::WAVEVARIABLE);
        mpND_Zcal12=getSafeNodeDataPtr(mpPal12, \
NodeMechanicRotational::CHARIMP);
        mpND_eqInertiaal12=getSafeNodeDataPtr(mpPal12, \
NodeMechanicRotational::EQINERTIA);
        //Port Par12
        mpND_torar12=getSafeNodeDataPtr(mpPar12, \
NodeMechanicRotational::TORQUE);
        mpND_thetaar12=getSafeNodeDataPtr(mpPar12, \
NodeMechanicRotational::ANGLE);
        mpND_war12=getSafeNodeDataPtr(mpPar12, \
NodeMechanicRotational::ANGULARVELOCITY);
        mpND_car12=getSafeNodeDataPtr(mpPar12, \
NodeMechanicRotational::WAVEVARIABLE);
        mpND_Zcar12=getSafeNodeDataPtr(mpPar12, \
NodeMechanicRotational::CHARIMP);
        mpND_eqInertiaar12=getSafeNodeDataPtr(mpPar12, \
NodeMechanicRotational::EQINERTIA);
        //Port Pal2
        mpND_toral2=getSafeNodeDataPtr(mpPal2, \
NodeMechanicRotational::TORQUE);
        mpND_thetaal2=getSafeNodeDataPtr(mpPal2, \
NodeMechanicRotational::ANGLE);
        mpND_wal2=getSafeNodeDataPtr(mpPal2, \
NodeMechanicRotational::ANGULARVELOCITY);
        mpND_cal2=getSafeNodeDataPtr(mpPal2, \
NodeMechanicRotational::WAVEVARIABLE);
        mpND_Zcal2=getSafeNodeDataPtr(mpPal2, \
NodeMechanicRotational::CHARIMP);
        mpND_eqInertiaal2=getSafeNodeDataPtr(mpPal2, \
NodeMechanicRotational::EQINERTIA);
        //Port Par2
        mpND_torar2=getSafeNodeDataPtr(mpPar2, \
NodeMechanicRotational::TORQUE);
        mpND_thetaar2=getSafeNodeDataPtr(mpPar2, \
NodeMechanicRotational::ANGLE);
        mpND_war2=getSafeNodeDataPtr(mpPar2, \
NodeMechanicRotational::ANGULARVELOCITY);
        mpND_car2=getSafeNodeDataPtr(mpPar2, \
NodeMechanicRotational::WAVEVARIABLE);
        mpND_Zcar2=getSafeNodeDataPtr(mpPar2, \
NodeMechanicRotational::CHARIMP);
        mpND_eqInertiaar2=getSafeNodeDataPtr(mpPar2, \
NodeMechanicRotational::EQINERTIA);
        //Port Pfin
        mpND_torfin=getSafeNodeDataPtr(mpPfin, \
NodeMechanicRotational::TORQUE);
        mpND_thetafin=getSafeNodeDataPtr(mpPfin, \
NodeMechanicRotational::ANGLE);
        mpND_wfin=getSafeNodeDataPtr(mpPfin, \
NodeMechanicRotational::ANGULARVELOCITY);
        mpND_cfin=getSafeNodeDataPtr(mpPfin, \
NodeMechanicRotational::WAVEVARIABLE);
        mpND_Zcfin=getSafeNodeDataPtr(mpPfin, \
NodeMechanicRotational::CHARIMP);
        mpND_eqInertiafin=getSafeNodeDataPtr(mpPfin, \
NodeMechanicRotational::EQINERTIA);
        //Read inputVariables pointers from nodes
        mpND_thrustl=getSafeNodeDataPtr(mpPthrustl, \
NodeSignal::VALUE,mthrustl);
        mpND_thrustr=getSafeNodeDataPtr(mpPthrustr, \
NodeSignal::VALUE,mthrustr);
        mpND_dezthrust=getSafeNodeDataPtr(mpPdezthrust, \
NodeSignal::VALUE,mdezthrust);
        mpND_Mfuel=getSafeNodeDataPtr(mpPMfuel, NodeSignal::VALUE,mMfuel);
        mpND_Mcargo=getSafeNodeDataPtr(mpPMcargo, NodeSignal::VALUE,mMcargo);
        mpND_rho=getSafeNodeDataPtr(mpPrho, NodeSignal::VALUE,mrho);
        mpND_vturbx=getSafeNodeDataPtr(mpPvturbx, NodeSignal::VALUE,mvturbx);
        mpND_vturby=getSafeNodeDataPtr(mpPvturby, NodeSignal::VALUE,mvturby);
        mpND_vturbz=getSafeNodeDataPtr(mpPvturbz, NodeSignal::VALUE,mvturbz);
        mpND_wturbx=getSafeNodeDataPtr(mpPwturbx, NodeSignal::VALUE,mwturbx);
        mpND_wturby=getSafeNodeDataPtr(mpPwturby, NodeSignal::VALUE,mwturby);
        mpND_wturbz=getSafeNodeDataPtr(mpPwturbz, NodeSignal::VALUE,mwturbz);
        //Read outputVariable pointers from nodes
        mpND_xcg=getSafeNodeDataPtr(mpPxcg, NodeSignal::VALUE);
        mpND_ycg=getSafeNodeDataPtr(mpPycg, NodeSignal::VALUE);
        mpND_zcg=getSafeNodeDataPtr(mpPzcg, NodeSignal::VALUE);
        mpND_vx=getSafeNodeDataPtr(mpPvx, NodeSignal::VALUE);
        mpND_vy=getSafeNodeDataPtr(mpPvy, NodeSignal::VALUE);
        mpND_vz=getSafeNodeDataPtr(mpPvz, NodeSignal::VALUE);
        mpND_Psi=getSafeNodeDataPtr(mpPPsi, NodeSignal::VALUE);
        mpND_Thetao=getSafeNodeDataPtr(mpPThetao, NodeSignal::VALUE);
        mpND_Phi=getSafeNodeDataPtr(mpPPhi, NodeSignal::VALUE);
        mpND_Ub=getSafeNodeDataPtr(mpPUb, NodeSignal::VALUE);
        mpND_Vb=getSafeNodeDataPtr(mpPVb, NodeSignal::VALUE);
        mpND_Wb=getSafeNodeDataPtr(mpPWb, NodeSignal::VALUE);
        mpND_Pb=getSafeNodeDataPtr(mpPPb, NodeSignal::VALUE);
        mpND_Qb=getSafeNodeDataPtr(mpPQb, NodeSignal::VALUE);
        mpND_Rb=getSafeNodeDataPtr(mpPRb, NodeSignal::VALUE);
        mpND_q0=getSafeNodeDataPtr(mpPq0, NodeSignal::VALUE);
        mpND_q1=getSafeNodeDataPtr(mpPq1, NodeSignal::VALUE);
        mpND_q2=getSafeNodeDataPtr(mpPq2, NodeSignal::VALUE);
        mpND_q3=getSafeNodeDataPtr(mpPq3, NodeSignal::VALUE);
        mpND_AlphaAttack=getSafeNodeDataPtr(mpPAlphaAttack, \
NodeSignal::VALUE);
        mpND_BetaSlip=getSafeNodeDataPtr(mpPBetaSlip, NodeSignal::VALUE);
        mpND_altitude=getSafeNodeDataPtr(mpPaltitude, NodeSignal::VALUE);
        mpND_gfx=getSafeNodeDataPtr(mpPgfx, NodeSignal::VALUE);
        mpND_gfy=getSafeNodeDataPtr(mpPgfy, NodeSignal::VALUE);
        mpND_gfz=getSafeNodeDataPtr(mpPgfz, NodeSignal::VALUE);
        mpND_CL1=getSafeNodeDataPtr(mpPCL1, NodeSignal::VALUE);
        mpND_Cd1=getSafeNodeDataPtr(mpPCd1, NodeSignal::VALUE);
        mpND_Fax=getSafeNodeDataPtr(mpPFax, NodeSignal::VALUE);
        mpND_Faz=getSafeNodeDataPtr(mpPFaz, NodeSignal::VALUE);

        //Read variables from nodes
        //Port Pal1
        toral1 = (*mpND_toral1);
        thetaal1 = (*mpND_thetaal1);
        wal1 = (*mpND_wal1);
        cal1 = (*mpND_cal1);
        Zcal1 = (*mpND_Zcal1);
        eqInertiaal1 = (*mpND_eqInertiaal1);
        //Port Par1
        torar1 = (*mpND_torar1);
        thetaar1 = (*mpND_thetaar1);
        war1 = (*mpND_war1);
        car1 = (*mpND_car1);
        Zcar1 = (*mpND_Zcar1);
        eqInertiaar1 = (*mpND_eqInertiaar1);
        //Port Pal12
        toral12 = (*mpND_toral12);
        thetaal12 = (*mpND_thetaal12);
        wal12 = (*mpND_wal12);
        cal12 = (*mpND_cal12);
        Zcal12 = (*mpND_Zcal12);
        eqInertiaal12 = (*mpND_eqInertiaal12);
        //Port Par12
        torar12 = (*mpND_torar12);
        thetaar12 = (*mpND_thetaar12);
        war12 = (*mpND_war12);
        car12 = (*mpND_car12);
        Zcar12 = (*mpND_Zcar12);
        eqInertiaar12 = (*mpND_eqInertiaar12);
        //Port Pal2
        toral2 = (*mpND_toral2);
        thetaal2 = (*mpND_thetaal2);
        wal2 = (*mpND_wal2);
        cal2 = (*mpND_cal2);
        Zcal2 = (*mpND_Zcal2);
        eqInertiaal2 = (*mpND_eqInertiaal2);
        //Port Par2
        torar2 = (*mpND_torar2);
        thetaar2 = (*mpND_thetaar2);
        war2 = (*mpND_war2);
        car2 = (*mpND_car2);
        Zcar2 = (*mpND_Zcar2);
        eqInertiaar2 = (*mpND_eqInertiaar2);
        //Port Pfin
        torfin = (*mpND_torfin);
        thetafin = (*mpND_thetafin);
        wfin = (*mpND_wfin);
        cfin = (*mpND_cfin);
        Zcfin = (*mpND_Zcfin);
        eqInertiafin = (*mpND_eqInertiafin);

        //Read inputVariables from nodes
        thrustl = (*mpND_thrustl);
        thrustr = (*mpND_thrustr);
        dezthrust = (*mpND_dezthrust);
        Mfuel = (*mpND_Mfuel);
        Mcargo = (*mpND_Mcargo);
        rho = (*mpND_rho);
        vturbx = (*mpND_vturbx);
        vturby = (*mpND_vturby);
        vturbz = (*mpND_vturbz);
        wturbx = (*mpND_wturbx);
        wturby = (*mpND_wturby);
        wturbz = (*mpND_wturbz);

        //Read outputVariables from nodes
        xcg = mpPxcg->getStartValue(NodeSignal::VALUE);
        ycg = mpPycg->getStartValue(NodeSignal::VALUE);
        zcg = mpPzcg->getStartValue(NodeSignal::VALUE);
        vx = mpPvx->getStartValue(NodeSignal::VALUE);
        vy = mpPvy->getStartValue(NodeSignal::VALUE);
        vz = mpPvz->getStartValue(NodeSignal::VALUE);
        Psi = mpPPsi->getStartValue(NodeSignal::VALUE);
        Thetao = mpPThetao->getStartValue(NodeSignal::VALUE);
        Phi = mpPPhi->getStartValue(NodeSignal::VALUE);
        Ub = mpPUb->getStartValue(NodeSignal::VALUE);
        Vb = mpPVb->getStartValue(NodeSignal::VALUE);
        Wb = mpPWb->getStartValue(NodeSignal::VALUE);
        Pb = mpPPb->getStartValue(NodeSignal::VALUE);
        Qb = mpPQb->getStartValue(NodeSignal::VALUE);
        Rb = mpPRb->getStartValue(NodeSignal::VALUE);
        q0 = mpPq0->getStartValue(NodeSignal::VALUE);
        q1 = mpPq1->getStartValue(NodeSignal::VALUE);
        q2 = mpPq2->getStartValue(NodeSignal::VALUE);
        q3 = mpPq3->getStartValue(NodeSignal::VALUE);
        AlphaAttack = mpPAlphaAttack->getStartValue(NodeSignal::VALUE);
        BetaSlip = mpPBetaSlip->getStartValue(NodeSignal::VALUE);
        altitude = mpPaltitude->getStartValue(NodeSignal::VALUE);
        gfx = mpPgfx->getStartValue(NodeSignal::VALUE);
        gfy = mpPgfy->getStartValue(NodeSignal::VALUE);
        gfz = mpPgfz->getStartValue(NodeSignal::VALUE);
        CL1 = mpPCL1->getStartValue(NodeSignal::VALUE);
        Cd1 = mpPCd1->getStartValue(NodeSignal::VALUE);
        Fax = mpPFax->getStartValue(NodeSignal::VALUE);
        Faz = mpPFaz->getStartValue(NodeSignal::VALUE);

        //InitialExpressions
        q0 = Cos(Phi/2.)*Cos(Psi/2.)*Cos(Thetao/2.) + \
Sin(Phi/2.)*Sin(Psi/2.)*Sin(Thetao/2.);
        q1 = Cos(Psi/2.)*Cos(Thetao/2.)*Sin(Phi/2.) - \
Cos(Phi/2.)*Sin(Psi/2.)*Sin(Thetao/2.);
        q2 = Cos(Thetao/2.)*Sin(Phi/2.)*Sin(Psi/2.) + \
Cos(Phi/2.)*Cos(Psi/2.)*Sin(Thetao/2.);
        q3 = Cos(Phi/2.)*Cos(Thetao/2.)*Sin(Psi/2.) - \
Cos(Psi/2.)*Sin(Phi/2.)*Sin(Thetao/2.);

        //LocalExpressions
        hthrust = mhthrust0*Sqrt(mS1);
        Ix = mAR1*mIx0*mMe*mS1;
        Ixz = mAR1*mIxz0*mMe*mS1;
        Iy = mIy0*mMe*mS1;
        Iz = (mIz0*mMe*mS1)/mAR1;
        lc1 = mlc10*Sqrt(mS1/mAR1);
        lc2 = mlc20*Sqrt(mS1/mAR1);
        lc12 = mlc120*Sqrt(mS1/mAR1);
        lcfin = mlcfin0*Sqrt(mS1/mAR1);
        rc1 = mrc10*Sqrt(mAR1*mS1);
        rc2 = mrc20*Sqrt(mAR1*mS1);
        rcfin = mrcfin0*Sqrt(mS1/mAR1);
        S2 = mS1*mS20;
        Sbh = mS1*mSbh0;
        Sbv = mS1*mSbv0;
        Sfin = mS1*mSfin0;
        xbach = Sqrt(mS1/mAR1)*mxbach0;
        xbacv = Sqrt(mS1/mAR1)*mxbacv0;
        xbcge = Sqrt(mS1/mAR1)*mxbcge0;
        xcargo = Sqrt(mS1/mAR1)*mxcargo0;
        xfuel = Sqrt(mS1/mAR1)*mxfuel0;
        xw1 = Sqrt(mS1/mAR1)*mxw10;
        xw2 = Sqrt(mS1/mAR1)*mxw20;
        xwfin = Sqrt(mS1/mAR1)*mxwfin0;
        yeng = Sqrt(mAR1*mS1)*myeng0;
        v = Sqrt(0.0001 + Power(Ub + vturbx,2) + Power(Vb + vturby,2) + \
Power(vturbz + Wb,2));
        Alpha = Atan2L(vturbz + Wb,0.0001 + Ub + vturbx);
        qpress = (rho*Power(v,2))/2.;
        Beta = Atan2L(Vb + vturby,Sqrt(0.0001 + Power(Ub + vturbx,2) + \
Power(vturbz + Wb,2)));
        mass = Mcargo + Mfuel + mMe;
        xbcg = (mMe*xbcge + Mcargo*xcargo + Mfuel*xfuel)/mass;
        Dragl1 = mS1*qpress*(mCd01/2. + mCdide1*Power(-mde10 + thetaal1,2) - \
mCdide112*(-mde10 + thetaal1)*(-mde120 + thetaal12) + mCdide12*Power(-mde120 \
+ thetaal12,2) + CDragInd(Alpha*mdah1 - \
mia1,mAR1,me1,mCLalpha1,map1,man1,mawp1,mawn1)/2.);
        Dragr1 = mS1*qpress*(mCd01/2. + mCdide1*Power(-mde10 + thetaar1,2) - \
mCdide112*(-mde10 + thetaar1)*(-mde120 + thetaar12) + mCdide12*Power(-mde120 \
+ thetaar12,2) + CDragInd(Alpha*mdah1 - \
mia1,mAR1,me1,mCLalpha1,map1,man1,mawp1,mawn1)/2.);
        Liftl1 = mS1*qpress*(mCLde1*thetaal1 + mCLde12*thetaal12 + \
CLift(Alpha*mdah1 - mia1,mCLalpha1,map1,man1,mawp1,mawn1)/2.);
        Liftr1 = mS1*qpress*(mCLde1*thetaar1 + mCLde12*thetaar12 + \
CLift(Alpha*mdah1 - mia1,mCLalpha1,map1,man1,mawp1,mawn1)/2.);
        Dragl2 = qpress*S2*(mCd02/2. + CDragInd(Alpha*mdah2 - \
mia2,mAR2,me2,mCLalpha2,map2,man2,mawp2,mawn2)/2.);
        Dragr2 = qpress*S2*(mCd02/2. + CDragInd(Alpha*mdah2 - \
mia2,mAR2,me2,mCLalpha2,map2,man2,mawp2,mawn2)/2.);
        Liftl2 = qpress*S2*(mCLde2*thetaal2 + CLift(Alpha*mdah2 - \
mia2,mCLalpha2,map2,man2,mawp2,mawn2)/2.);
        Liftr2 = qpress*S2*(mCLde2*thetaar2 + CLift(Alpha*mdah2 - \
mia2,mCLalpha2,map2,man2,mawp2,mawn2)/2.);
        Liftb = mCLalphabh*qpress*Sbh*Sin(Alpha);
        Dragb = mCd0b*qpress*Sbh;
        Cfin = qpress*Sfin*CLift(-Beta - \
(mCLdefin*thetafin)/mCLalphafin,mCLalphafin,mafin,mafin,mawfin,mawfin);
        Dragfin = mCd0fin*qpress*Sfin;
        Mdvtheta = (mCLalpha2*qpress*S2*Power(-xbcg + xw2,2))/(0.1 + v);
        Mdvpsi = (mCLalphafin*qpress*Sfin*Power(-xbcg + xwfin,2))/(0.1 + v);
        Fx = (-Dragb - Dragfin - Dragl1 - Dragl2 - Dragr1 - \
Dragr2)*Cos(Alpha)*Cos(Beta) + (thrustl + thrustr)*Cos(dezthrust) - (-Liftb - \
Liftl1 - Liftl2 - Liftr1 - Liftr2)*Sin(Alpha) - Cos(Alpha)*Sin(Beta)*(-Cfin + \
mCLalphabv*qpress*Sbv*Sin(Beta));
        Fy = (-Dragb - Dragfin - Dragl1 - Dragl2 - Dragr1 - Dragr2)*Sin(Beta) \
+ Cos(Beta)*(-Cfin + mCLalphabv*qpress*Sbv*Sin(Beta));
        Fz = (-Liftb - Liftl1 - Liftl2 - Liftr1 - Liftr2)*Cos(Alpha) + \
(-Dragb - Dragfin - Dragl1 - Dragl2 - Dragr1 - Dragr2)*Cos(Beta)*Sin(Alpha) - \
Sin(Alpha)*Sin(Beta)*(-Cfin + mCLalphabv*qpress*Sbv*Sin(Beta)) + (thrustl + \
thrustr)*Sin(dezthrust);
        Lb = (Liftl1 - Liftr1)*rc1 + (Liftl2 - Liftr2)*rc2 - \
(0.12249999999999998*qpress*(mAR1*mCLalpha1*Power(mS1,2) + \
mAR2*mCLalpha2*Power(S2,2))*(Pb + wturbx))/(0.1 + v) + (thrustl - \
thrustr)*yeng*Sin(dezthrust);
        Mb = -(Mdvtheta*(Qb + wturby)) + mS1*qpress*(-(mCmde1*thetaal1) - \
mCmde12*thetaal12 - mCmde1*thetaar1 - mCmde12*thetaar12 + CMoment(Alpha*mdah1 \
- mia1,mCm01,mCmfs1,map1,man1,mawp1,mawn1)) + (xbcg - xw1)*((Liftl1 + \
Liftr1)*Cos(Alpha) + (Dragl1 + Dragr1)*Sin(Alpha)) + (xbcg - xw2)*((Liftl2 + \
Liftr2)*Cos(Alpha) - (Dragl2 + Dragr2)*Sin(Alpha)) + (thrustl + \
thrustr)*(hthrust - xbcg)*Sin(dezthrust);
        Nb = -(Mdvpsi*(Rb + wturbz)) - Cfin*(-xbcg + xwfin) + (thrustl - \
thrustr)*yeng*Cos(dezthrust) + rc1*((-Dragl1 + Dragr1)*Cos(Alpha) + (-Liftl1 \
+ Liftr1)*Sin(Alpha)) + rc2*((-Dragl2 + Dragr2)*Cos(Alpha) + (-Liftl2 + \
Liftr2)*Sin(Alpha));

        //Initialize delays
        delayParts1[1] = (-(Fx*mTimestep) + 2*mass*mg0*mTimestep*q0*q2 - \
2*mass*mg0*mTimestep*q1*q3 - 2*mass*Ub - mass*mTimestep*Rb*Vb + \
mass*mTimestep*Qb*Wb - 2*mkground*mTimestep*q0*q2*zcg*onPositive(zcg) + \
2*mkground*mTimestep*q1*q3*zcg*onPositive(zcg))/(2.*mass);
        mDelayedPart11.initialize(mNstep,delayParts1[1]);
        delayParts2[1] = (-(Fy*mTimestep) - 2*mass*mg0*mTimestep*q0*q1 - \
2*mass*mg0*mTimestep*q2*q3 + mass*mTimestep*Rb*Ub - 2*mass*Vb - \
mass*mTimestep*Pb*Wb + 2*mkground*mTimestep*q0*q1*zcg*onPositive(zcg) + \
2*mkground*mTimestep*q2*q3*zcg*onPositive(zcg))/(2.*mass);
        mDelayedPart21.initialize(mNstep,delayParts2[1]);
        delayParts3[1] = (-(Fz*mTimestep) - mass*mg0*mTimestep*Power(q0,2) + \
mass*mg0*mTimestep*Power(q1,2) + mass*mg0*mTimestep*Power(q2,2) - \
mass*mg0*mTimestep*Power(q3,2) - mass*mTimestep*Qb*Ub + mass*mTimestep*Pb*Vb \
- 2*mass*Wb + mkground*mTimestep*Power(q0,2)*zcg*onPositive(zcg) - \
mkground*mTimestep*Power(q1,2)*zcg*onPositive(zcg) - \
mkground*mTimestep*Power(q2,2)*zcg*onPositive(zcg) + \
mkground*mTimestep*Power(q3,2)*zcg*onPositive(zcg))/(2.*mass);
        mDelayedPart31.initialize(mNstep,delayParts3[1]);
        delayParts4[1] = (Iz*Lb*mTimestep + Ixz*mTimestep*Nb - \
2*Power(Ixz,2)*Pb + 2*Ix*Iz*Pb + Ix*Ixz*mTimestep*Pb*Qb - \
Ixz*Iy*mTimestep*Pb*Qb + Ixz*Iz*mTimestep*Pb*Qb - \
Power(Ixz,2)*mTimestep*Qb*Rb + Iy*Iz*mTimestep*Qb*Rb - \
Power(Iz,2)*mTimestep*Qb*Rb)/(2*Power(Ixz,2) - 2*Ix*Iz + Ix*Ixz*mTimestep*Qb \
- Ixz*Iy*mTimestep*Qb + Ixz*Iz*mTimestep*Qb);
        mDelayedPart41.initialize(mNstep,delayParts4[1]);
        delayParts5[1] = (-(Mb*mTimestep) + Ixz*mTimestep*Power(Pb,2) - \
2*Iy*Qb + Ix*mTimestep*Pb*Rb - Iz*mTimestep*Pb*Rb - \
Ixz*mTimestep*Power(Rb,2))/(2.*Iy);
        mDelayedPart51.initialize(mNstep,delayParts5[1]);
        delayParts6[1] = (Ixz*Lb*mTimestep + Ix*mTimestep*Nb + \
Power(Ix,2)*mTimestep*Pb*Qb + Power(Ixz,2)*mTimestep*Pb*Qb - \
Ix*Iy*mTimestep*Pb*Qb - 2*Power(Ixz,2)*Rb + 2*Ix*Iz*Rb - \
Ix*Ixz*mTimestep*Qb*Rb + Ixz*Iy*mTimestep*Qb*Rb - \
Ixz*Iz*mTimestep*Qb*Rb)/(2*Power(Ixz,2) - 2*Ix*Iz - Ix*Ixz*mTimestep*Qb + \
Ixz*Iy*mTimestep*Qb - Ixz*Iz*mTimestep*Qb);
        mDelayedPart61.initialize(mNstep,delayParts6[1]);
        delayParts7[1] = (-4*q0 + mTimestep*Pb*q1 + mTimestep*q2*Qb + \
mTimestep*q3*Rb)/4.;
        mDelayedPart71.initialize(mNstep,delayParts7[1]);
        delayParts8[1] = (-(mTimestep*Pb*q0) - 4*q1 + mTimestep*q3*Qb - \
mTimestep*q2*Rb)/4.;
        mDelayedPart81.initialize(mNstep,delayParts8[1]);
        delayParts9[1] = (-4*q2 - mTimestep*Pb*q3 - mTimestep*q0*Qb + \
mTimestep*q1*Rb)/4.;
        mDelayedPart91.initialize(mNstep,delayParts9[1]);
        delayParts10[1] = (mTimestep*Pb*q2 - 4*q3 - mTimestep*q1*Qb - \
mTimestep*q0*Rb)/4.;
        mDelayedPart101.initialize(mNstep,delayParts10[1]);
        delayParts11[1] = (-(mTimestep*Power(q0,2)*Ub) - \
mTimestep*Power(q1,2)*Ub + mTimestep*Power(q2,2)*Ub + \
mTimestep*Power(q3,2)*Ub - 2*mTimestep*q1*q2*Vb + 2*mTimestep*q0*q3*Vb - \
2*mTimestep*q0*q2*Wb - 2*mTimestep*q1*q3*Wb - 2*xcg)/2.;
        mDelayedPart111.initialize(mNstep,delayParts11[1]);
        delayParts12[1] = (-2*mTimestep*q1*q2*Ub - 2*mTimestep*q0*q3*Ub - \
mTimestep*Power(q0,2)*Vb + mTimestep*Power(q1,2)*Vb - \
mTimestep*Power(q2,2)*Vb + mTimestep*Power(q3,2)*Vb + 2*mTimestep*q0*q1*Wb - \
2*mTimestep*q2*q3*Wb - 2*ycg)/2.;
        mDelayedPart121.initialize(mNstep,delayParts12[1]);
        delayParts13[1] = (2*mTimestep*q0*q2*Ub - 2*mTimestep*q1*q3*Ub - \
2*mTimestep*q0*q1*Vb - 2*mTimestep*q2*q3*Vb - mTimestep*Power(q0,2)*Wb + \
mTimestep*Power(q1,2)*Wb + mTimestep*Power(q2,2)*Wb - \
mTimestep*Power(q3,2)*Wb - 2*zcg)/2.;
        mDelayedPart131.initialize(mNstep,delayParts13[1]);

        delayedPart[1][1] = delayParts1[1];
        delayedPart[2][1] = delayParts2[1];
        delayedPart[3][1] = delayParts3[1];
        delayedPart[4][1] = delayParts4[1];
        delayedPart[5][1] = delayParts5[1];
        delayedPart[6][1] = delayParts6[1];
        delayedPart[7][1] = delayParts7[1];
        delayedPart[8][1] = delayParts8[1];
        delayedPart[9][1] = delayParts9[1];
        delayedPart[10][1] = delayParts10[1];
        delayedPart[11][1] = delayParts11[1];
        delayedPart[12][1] = delayParts12[1];
        delayedPart[13][1] = delayParts13[1];
     }
    void simulateOneTimestep()
     {
        Vec stateVar(13);
        Vec stateVark(13);
        Vec deltaStateVar(13);

        //Read variables from nodes
        //Port Pal1
        toral1 = (*mpND_toral1);
        thetaal1 = (*mpND_thetaal1);
        wal1 = (*mpND_wal1);
        eqInertiaal1 = (*mpND_eqInertiaal1);
        //Port Par1
        torar1 = (*mpND_torar1);
        thetaar1 = (*mpND_thetaar1);
        war1 = (*mpND_war1);
        eqInertiaar1 = (*mpND_eqInertiaar1);
        //Port Pal12
        toral12 = (*mpND_toral12);
        thetaal12 = (*mpND_thetaal12);
        wal12 = (*mpND_wal12);
        eqInertiaal12 = (*mpND_eqInertiaal12);
        //Port Par12
        torar12 = (*mpND_torar12);
        thetaar12 = (*mpND_thetaar12);
        war12 = (*mpND_war12);
        eqInertiaar12 = (*mpND_eqInertiaar12);
        //Port Pal2
        toral2 = (*mpND_toral2);
        thetaal2 = (*mpND_thetaal2);
        wal2 = (*mpND_wal2);
        eqInertiaal2 = (*mpND_eqInertiaal2);
        //Port Par2
        torar2 = (*mpND_torar2);
        thetaar2 = (*mpND_thetaar2);
        war2 = (*mpND_war2);
        eqInertiaar2 = (*mpND_eqInertiaar2);
        //Port Pfin
        torfin = (*mpND_torfin);
        thetafin = (*mpND_thetafin);
        wfin = (*mpND_wfin);
        eqInertiafin = (*mpND_eqInertiafin);

        //Read inputVariables from nodes
        thrustl = (*mpND_thrustl);
        thrustr = (*mpND_thrustr);
        dezthrust = (*mpND_dezthrust);
        Mfuel = (*mpND_Mfuel);
        Mcargo = (*mpND_Mcargo);
        rho = (*mpND_rho);
        vturbx = (*mpND_vturbx);
        vturby = (*mpND_vturby);
        vturbz = (*mpND_vturbz);
        wturbx = (*mpND_wturbx);
        wturby = (*mpND_wturby);
        wturbz = (*mpND_wturbz);

        //LocalExpressions
        hthrust = mhthrust0*Sqrt(mS1);
        Ix = mAR1*mIx0*mMe*mS1;
        Ixz = mAR1*mIxz0*mMe*mS1;
        Iy = mIy0*mMe*mS1;
        Iz = (mIz0*mMe*mS1)/mAR1;
        lc1 = mlc10*Sqrt(mS1/mAR1);
        lc2 = mlc20*Sqrt(mS1/mAR1);
        lc12 = mlc120*Sqrt(mS1/mAR1);
        lcfin = mlcfin0*Sqrt(mS1/mAR1);
        rc1 = mrc10*Sqrt(mAR1*mS1);
        rc2 = mrc20*Sqrt(mAR1*mS1);
        rcfin = mrcfin0*Sqrt(mS1/mAR1);
        S2 = mS1*mS20;
        Sbh = mS1*mSbh0;
        Sbv = mS1*mSbv0;
        Sfin = mS1*mSfin0;
        xbach = Sqrt(mS1/mAR1)*mxbach0;
        xbacv = Sqrt(mS1/mAR1)*mxbacv0;
        xbcge = Sqrt(mS1/mAR1)*mxbcge0;
        xcargo = Sqrt(mS1/mAR1)*mxcargo0;
        xfuel = Sqrt(mS1/mAR1)*mxfuel0;
        xw1 = Sqrt(mS1/mAR1)*mxw10;
        xw2 = Sqrt(mS1/mAR1)*mxw20;
        xwfin = Sqrt(mS1/mAR1)*mxwfin0;
        yeng = Sqrt(mAR1*mS1)*myeng0;
        v = Sqrt(0.0001 + Power(Ub + vturbx,2) + Power(Vb + vturby,2) + \
Power(vturbz + Wb,2));
        Alpha = Atan2L(vturbz + Wb,0.0001 + Ub + vturbx);
        qpress = (rho*Power(v,2))/2.;
        Beta = Atan2L(Vb + vturby,Sqrt(0.0001 + Power(Ub + vturbx,2) + \
Power(vturbz + Wb,2)));
        mass = Mcargo + Mfuel + mMe;
        xbcg = (mMe*xbcge + Mcargo*xcargo + Mfuel*xfuel)/mass;
        Dragl1 = mS1*qpress*(mCd01/2. + mCdide1*Power(-mde10 + thetaal1,2) - \
mCdide112*(-mde10 + thetaal1)*(-mde120 + thetaal12) + mCdide12*Power(-mde120 \
+ thetaal12,2) + CDragInd(Alpha*mdah1 - \
mia1,mAR1,me1,mCLalpha1,map1,man1,mawp1,mawn1)/2.);
        Dragr1 = mS1*qpress*(mCd01/2. + mCdide1*Power(-mde10 + thetaar1,2) - \
mCdide112*(-mde10 + thetaar1)*(-mde120 + thetaar12) + mCdide12*Power(-mde120 \
+ thetaar12,2) + CDragInd(Alpha*mdah1 - \
mia1,mAR1,me1,mCLalpha1,map1,man1,mawp1,mawn1)/2.);
        Liftl1 = mS1*qpress*(mCLde1*thetaal1 + mCLde12*thetaal12 + \
CLift(Alpha*mdah1 - mia1,mCLalpha1,map1,man1,mawp1,mawn1)/2.);
        Liftr1 = mS1*qpress*(mCLde1*thetaar1 + mCLde12*thetaar12 + \
CLift(Alpha*mdah1 - mia1,mCLalpha1,map1,man1,mawp1,mawn1)/2.);
        Dragl2 = qpress*S2*(mCd02/2. + CDragInd(Alpha*mdah2 - \
mia2,mAR2,me2,mCLalpha2,map2,man2,mawp2,mawn2)/2.);
        Dragr2 = qpress*S2*(mCd02/2. + CDragInd(Alpha*mdah2 - \
mia2,mAR2,me2,mCLalpha2,map2,man2,mawp2,mawn2)/2.);
        Liftl2 = qpress*S2*(mCLde2*thetaal2 + CLift(Alpha*mdah2 - \
mia2,mCLalpha2,map2,man2,mawp2,mawn2)/2.);
        Liftr2 = qpress*S2*(mCLde2*thetaar2 + CLift(Alpha*mdah2 - \
mia2,mCLalpha2,map2,man2,mawp2,mawn2)/2.);
        Liftb = mCLalphabh*qpress*Sbh*Sin(Alpha);
        Dragb = mCd0b*qpress*Sbh;
        Cfin = qpress*Sfin*CLift(-Beta - \
(mCLdefin*thetafin)/mCLalphafin,mCLalphafin,mafin,mafin,mawfin,mawfin);
        Dragfin = mCd0fin*qpress*Sfin;
        Mdvtheta = (mCLalpha2*qpress*S2*Power(-xbcg + xw2,2))/(0.1 + v);
        Mdvpsi = (mCLalphafin*qpress*Sfin*Power(-xbcg + xwfin,2))/(0.1 + v);
        Fx = (-Dragb - Dragfin - Dragl1 - Dragl2 - Dragr1 - \
Dragr2)*Cos(Alpha)*Cos(Beta) + (thrustl + thrustr)*Cos(dezthrust) - (-Liftb - \
Liftl1 - Liftl2 - Liftr1 - Liftr2)*Sin(Alpha) - Cos(Alpha)*Sin(Beta)*(-Cfin + \
mCLalphabv*qpress*Sbv*Sin(Beta));
        Fy = (-Dragb - Dragfin - Dragl1 - Dragl2 - Dragr1 - Dragr2)*Sin(Beta) \
+ Cos(Beta)*(-Cfin + mCLalphabv*qpress*Sbv*Sin(Beta));
        Fz = (-Liftb - Liftl1 - Liftl2 - Liftr1 - Liftr2)*Cos(Alpha) + \
(-Dragb - Dragfin - Dragl1 - Dragl2 - Dragr1 - Dragr2)*Cos(Beta)*Sin(Alpha) - \
Sin(Alpha)*Sin(Beta)*(-Cfin + mCLalphabv*qpress*Sbv*Sin(Beta)) + (thrustl + \
thrustr)*Sin(dezthrust);
        Lb = (Liftl1 - Liftr1)*rc1 + (Liftl2 - Liftr2)*rc2 - \
(0.12249999999999998*qpress*(mAR1*mCLalpha1*Power(mS1,2) + \
mAR2*mCLalpha2*Power(S2,2))*(Pb + wturbx))/(0.1 + v) + (thrustl - \
thrustr)*yeng*Sin(dezthrust);
        Mb = -(Mdvtheta*(Qb + wturby)) + mS1*qpress*(-(mCmde1*thetaal1) - \
mCmde12*thetaal12 - mCmde1*thetaar1 - mCmde12*thetaar12 + CMoment(Alpha*mdah1 \
- mia1,mCm01,mCmfs1,map1,man1,mawp1,mawn1)) + (xbcg - xw1)*((Liftl1 + \
Liftr1)*Cos(Alpha) + (Dragl1 + Dragr1)*Sin(Alpha)) + (xbcg - xw2)*((Liftl2 + \
Liftr2)*Cos(Alpha) - (Dragl2 + Dragr2)*Sin(Alpha)) + (thrustl + \
thrustr)*(hthrust - xbcg)*Sin(dezthrust);
        Nb = -(Mdvpsi*(Rb + wturbz)) - Cfin*(-xbcg + xwfin) + (thrustl - \
thrustr)*yeng*Cos(dezthrust) + rc1*((-Dragl1 + Dragr1)*Cos(Alpha) + (-Liftl1 \
+ Liftr1)*Sin(Alpha)) + rc2*((-Dragl2 + Dragr2)*Cos(Alpha) + (-Liftl2 + \
Liftr2)*Sin(Alpha));

        //Initializing variable vector for Newton-Raphson
        stateVark[0] = Ub;
        stateVark[1] = Vb;
        stateVark[2] = Wb;
        stateVark[3] = Pb;
        stateVark[4] = Qb;
        stateVark[5] = Rb;
        stateVark[6] = q0;
        stateVark[7] = q1;
        stateVark[8] = q2;
        stateVark[9] = q3;
        stateVark[10] = xcg;
        stateVark[11] = ycg;
        stateVark[12] = zcg;

        //Iterative solution using Newton-Rapshson
        for(iter=1;iter<=mNoiter;iter++)
        {
         //Aircraft6DOFS
         //Differential-algebraic system of equation parts

          //Assemble differential-algebraic equations
          systemEquations[0] =Ub - (mTimestep*(Fx + mass*(-2*mg0*q0*q2 + \
2*mg0*q1*q3 + Rb*Vb - Qb*Wb) + 2*mkground*(q0*q2 - \
q1*q3)*zcg*onPositive(zcg)))/(2.*mass) + delayedPart[1][1];
          systemEquations[1] =Vb - (mTimestep*(Fy + mass*(2*mg0*q0*q1 + \
2*mg0*q2*q3 - Rb*Ub + Pb*Wb) - 2*mkground*(q0*q1 + \
q2*q3)*zcg*onPositive(zcg)))/(2.*mass) + delayedPart[2][1];
          systemEquations[2] =Wb - (mTimestep*(Fz + mass*(mg0*(Power(q0,2) - \
Power(q1,2) - Power(q2,2) + Power(q3,2)) + Qb*Ub - Pb*Vb) + \
mkground*(-Power(q0,2) + Power(q1,2) + Power(q2,2) - \
Power(q3,2))*zcg*onPositive(zcg)))/(2.*mass) + delayedPart[3][1];
          systemEquations[3] =Pb + (mTimestep*(-(Power(Iz,2)*Qb*Rb) + Ixz*(Nb \
- Ixz*Qb*Rb) + Iz*(Lb + Iy*Qb*Rb)))/(2*Power(Ixz,2) - 2*Ix*Iz + Ixz*(Ix - Iy \
+ Iz)*mTimestep*Qb) + delayedPart[4][1];
          systemEquations[4] =Qb - (mTimestep*(Mb + (-Ix + Iz)*Pb*Rb + \
Ixz*(-Power(Pb,2) + Power(Rb,2))))/(2.*Iy) + delayedPart[5][1];
          systemEquations[5] =-((mTimestep*(Ixz*Lb + Power(Ixz,2)*Pb*Qb + \
Ix*(Nb + (Ix - Iy)*Pb*Qb)))/(-2*Power(Ixz,2) + 2*Ix*Iz + Ixz*(Ix - Iy + \
Iz)*mTimestep*Qb)) + Rb + delayedPart[6][1];
          systemEquations[6] =q0 + (mTimestep*(Pb*q1 + q2*Qb + q3*Rb))/4. + \
delayedPart[7][1];
          systemEquations[7] =q1 - (mTimestep*(Pb*q0 - q3*Qb + q2*Rb))/4. + \
delayedPart[8][1];
          systemEquations[8] =q2 - (mTimestep*(Pb*q3 + q0*Qb - q1*Rb))/4. + \
delayedPart[9][1];
          systemEquations[9] =q3 + (mTimestep*(Pb*q2 - q1*Qb - q0*Rb))/4. + \
delayedPart[10][1];
          systemEquations[10] =-(mTimestep*(Power(q0,2)*Ub + Power(q1,2)*Ub - \
(Power(q2,2) + Power(q3,2))*Ub + q0*(-2*q3*Vb + 2*q2*Wb) + 2*q1*(q2*Vb + \
q3*Wb)))/2. + xcg + delayedPart[11][1];
          systemEquations[11] =(mTimestep*(-2*q1*q2*Ub - 2*q0*q3*Ub - \
Power(q0,2)*Vb + Power(q1,2)*Vb - Power(q2,2)*Vb + Power(q3,2)*Vb + \
2*q0*q1*Wb - 2*q2*q3*Wb))/2. + ycg + delayedPart[12][1];
          systemEquations[12] =-(mTimestep*(-2*q0*q2*Ub + 2*q1*q3*Ub + \
2*q0*q1*Vb + 2*q2*q3*Vb + Power(q0,2)*Wb - Power(q1,2)*Wb - Power(q2,2)*Wb + \
Power(q3,2)*Wb))/2. + zcg + delayedPart[13][1];

          //Jacobian matrix
          jacobianMatrix[0][0] = 1;
          jacobianMatrix[0][1] = -(mTimestep*Rb)/2.;
          jacobianMatrix[0][2] = (mTimestep*Qb)/2.;
          jacobianMatrix[0][3] = 0;
          jacobianMatrix[0][4] = (mTimestep*Wb)/2.;
          jacobianMatrix[0][5] = -(mTimestep*Vb)/2.;
          jacobianMatrix[0][6] = -(mTimestep*(-2*mass*mg0*q2 + \
2*mkground*q2*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[0][7] = -(mTimestep*(2*mass*mg0*q3 - \
2*mkground*q3*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[0][8] = -(mTimestep*(-2*mass*mg0*q0 + \
2*mkground*q0*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[0][9] = -(mTimestep*(2*mass*mg0*q1 - \
2*mkground*q1*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[0][10] = 0;
          jacobianMatrix[0][11] = 0;
          jacobianMatrix[0][12] = -((mkground*mTimestep*(q0*q2 - \
q1*q3)*onPositive(zcg))/mass);
          jacobianMatrix[1][0] = (mTimestep*Rb)/2.;
          jacobianMatrix[1][1] = 1;
          jacobianMatrix[1][2] = -(mTimestep*Pb)/2.;
          jacobianMatrix[1][3] = -(mTimestep*Wb)/2.;
          jacobianMatrix[1][4] = 0;
          jacobianMatrix[1][5] = (mTimestep*Ub)/2.;
          jacobianMatrix[1][6] = -(mTimestep*(2*mass*mg0*q1 - \
2*mkground*q1*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[1][7] = -(mTimestep*(2*mass*mg0*q0 - \
2*mkground*q0*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[1][8] = -(mTimestep*(2*mass*mg0*q3 - \
2*mkground*q3*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[1][9] = -(mTimestep*(2*mass*mg0*q2 - \
2*mkground*q2*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[1][10] = 0;
          jacobianMatrix[1][11] = 0;
          jacobianMatrix[1][12] = (mkground*mTimestep*(q0*q1 + \
q2*q3)*onPositive(zcg))/mass;
          jacobianMatrix[2][0] = -(mTimestep*Qb)/2.;
          jacobianMatrix[2][1] = (mTimestep*Pb)/2.;
          jacobianMatrix[2][2] = 1;
          jacobianMatrix[2][3] = (mTimestep*Vb)/2.;
          jacobianMatrix[2][4] = -(mTimestep*Ub)/2.;
          jacobianMatrix[2][5] = 0;
          jacobianMatrix[2][6] = -(mTimestep*(2*mass*mg0*q0 - \
2*mkground*q0*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[2][7] = -(mTimestep*(-2*mass*mg0*q1 + \
2*mkground*q1*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[2][8] = -(mTimestep*(-2*mass*mg0*q2 + \
2*mkground*q2*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[2][9] = -(mTimestep*(2*mass*mg0*q3 - \
2*mkground*q3*zcg*onPositive(zcg)))/(2.*mass);
          jacobianMatrix[2][10] = 0;
          jacobianMatrix[2][11] = 0;
          jacobianMatrix[2][12] = -(mkground*mTimestep*(-Power(q0,2) + \
Power(q1,2) + Power(q2,2) - Power(q3,2))*onPositive(zcg))/(2.*mass);
          jacobianMatrix[3][0] = 0;
          jacobianMatrix[3][1] = 0;
          jacobianMatrix[3][2] = 0;
          jacobianMatrix[3][3] = 1;
          jacobianMatrix[3][4] = (mTimestep*(-(Power(Ixz,2)*Rb) + Iy*Iz*Rb - \
Power(Iz,2)*Rb))/(2*Power(Ixz,2) - 2*Ix*Iz + Ixz*(Ix - Iy + Iz)*mTimestep*Qb) \
- (Ixz*(Ix - Iy + Iz)*Power(mTimestep,2)*(-(Power(Iz,2)*Qb*Rb) + Ixz*(Nb - \
Ixz*Qb*Rb) + Iz*(Lb + Iy*Qb*Rb)))/Power(2*Power(Ixz,2) - 2*Ix*Iz + Ixz*(Ix - \
Iy + Iz)*mTimestep*Qb,2);
          jacobianMatrix[3][5] = (mTimestep*(-(Power(Ixz,2)*Qb) + Iy*Iz*Qb - \
Power(Iz,2)*Qb))/(2*Power(Ixz,2) - 2*Ix*Iz + Ixz*(Ix - Iy + \
Iz)*mTimestep*Qb);
          jacobianMatrix[3][6] = 0;
          jacobianMatrix[3][7] = 0;
          jacobianMatrix[3][8] = 0;
          jacobianMatrix[3][9] = 0;
          jacobianMatrix[3][10] = 0;
          jacobianMatrix[3][11] = 0;
          jacobianMatrix[3][12] = 0;
          jacobianMatrix[4][0] = 0;
          jacobianMatrix[4][1] = 0;
          jacobianMatrix[4][2] = 0;
          jacobianMatrix[4][3] = -(mTimestep*(-2*Ixz*Pb + (-Ix + \
Iz)*Rb))/(2.*Iy);
          jacobianMatrix[4][4] = 1;
          jacobianMatrix[4][5] = -(mTimestep*((-Ix + Iz)*Pb + \
2*Ixz*Rb))/(2.*Iy);
          jacobianMatrix[4][6] = 0;
          jacobianMatrix[4][7] = 0;
          jacobianMatrix[4][8] = 0;
          jacobianMatrix[4][9] = 0;
          jacobianMatrix[4][10] = 0;
          jacobianMatrix[4][11] = 0;
          jacobianMatrix[4][12] = 0;
          jacobianMatrix[5][0] = 0;
          jacobianMatrix[5][1] = 0;
          jacobianMatrix[5][2] = 0;
          jacobianMatrix[5][3] = -((mTimestep*(Power(Ixz,2)*Qb + Ix*(Ix - \
Iy)*Qb))/(-2*Power(Ixz,2) + 2*Ix*Iz + Ixz*(Ix - Iy + Iz)*mTimestep*Qb));
          jacobianMatrix[5][4] = -((mTimestep*(Power(Ixz,2)*Pb + Ix*(Ix - \
Iy)*Pb))/(-2*Power(Ixz,2) + 2*Ix*Iz + Ixz*(Ix - Iy + Iz)*mTimestep*Qb)) + \
(Ixz*(Ix - Iy + Iz)*Power(mTimestep,2)*(Ixz*Lb + Power(Ixz,2)*Pb*Qb + Ix*(Nb \
+ (Ix - Iy)*Pb*Qb)))/Power(-2*Power(Ixz,2) + 2*Ix*Iz + Ixz*(Ix - Iy + \
Iz)*mTimestep*Qb,2);
          jacobianMatrix[5][5] = 1;
          jacobianMatrix[5][6] = 0;
          jacobianMatrix[5][7] = 0;
          jacobianMatrix[5][8] = 0;
          jacobianMatrix[5][9] = 0;
          jacobianMatrix[5][10] = 0;
          jacobianMatrix[5][11] = 0;
          jacobianMatrix[5][12] = 0;
          jacobianMatrix[6][0] = 0;
          jacobianMatrix[6][1] = 0;
          jacobianMatrix[6][2] = 0;
          jacobianMatrix[6][3] = (mTimestep*q1)/4.;
          jacobianMatrix[6][4] = (mTimestep*q2)/4.;
          jacobianMatrix[6][5] = (mTimestep*q3)/4.;
          jacobianMatrix[6][6] = 1;
          jacobianMatrix[6][7] = (mTimestep*Pb)/4.;
          jacobianMatrix[6][8] = (mTimestep*Qb)/4.;
          jacobianMatrix[6][9] = (mTimestep*Rb)/4.;
          jacobianMatrix[6][10] = 0;
          jacobianMatrix[6][11] = 0;
          jacobianMatrix[6][12] = 0;
          jacobianMatrix[7][0] = 0;
          jacobianMatrix[7][1] = 0;
          jacobianMatrix[7][2] = 0;
          jacobianMatrix[7][3] = -(mTimestep*q0)/4.;
          jacobianMatrix[7][4] = (mTimestep*q3)/4.;
          jacobianMatrix[7][5] = -(mTimestep*q2)/4.;
          jacobianMatrix[7][6] = -(mTimestep*Pb)/4.;
          jacobianMatrix[7][7] = 1;
          jacobianMatrix[7][8] = -(mTimestep*Rb)/4.;
          jacobianMatrix[7][9] = (mTimestep*Qb)/4.;
          jacobianMatrix[7][10] = 0;
          jacobianMatrix[7][11] = 0;
          jacobianMatrix[7][12] = 0;
          jacobianMatrix[8][0] = 0;
          jacobianMatrix[8][1] = 0;
          jacobianMatrix[8][2] = 0;
          jacobianMatrix[8][3] = -(mTimestep*q3)/4.;
          jacobianMatrix[8][4] = -(mTimestep*q0)/4.;
          jacobianMatrix[8][5] = (mTimestep*q1)/4.;
          jacobianMatrix[8][6] = -(mTimestep*Qb)/4.;
          jacobianMatrix[8][7] = (mTimestep*Rb)/4.;
          jacobianMatrix[8][8] = 1;
          jacobianMatrix[8][9] = -(mTimestep*Pb)/4.;
          jacobianMatrix[8][10] = 0;
          jacobianMatrix[8][11] = 0;
          jacobianMatrix[8][12] = 0;
          jacobianMatrix[9][0] = 0;
          jacobianMatrix[9][1] = 0;
          jacobianMatrix[9][2] = 0;
          jacobianMatrix[9][3] = (mTimestep*q2)/4.;
          jacobianMatrix[9][4] = -(mTimestep*q1)/4.;
          jacobianMatrix[9][5] = -(mTimestep*q0)/4.;
          jacobianMatrix[9][6] = -(mTimestep*Rb)/4.;
          jacobianMatrix[9][7] = -(mTimestep*Qb)/4.;
          jacobianMatrix[9][8] = (mTimestep*Pb)/4.;
          jacobianMatrix[9][9] = 1;
          jacobianMatrix[9][10] = 0;
          jacobianMatrix[9][11] = 0;
          jacobianMatrix[9][12] = 0;
          jacobianMatrix[10][0] = -(mTimestep*(Power(q0,2) + Power(q1,2) - \
Power(q2,2) - Power(q3,2)))/2.;
          jacobianMatrix[10][1] = -(mTimestep*(2*q1*q2 - 2*q0*q3))/2.;
          jacobianMatrix[10][2] = -(mTimestep*(2*q0*q2 + 2*q1*q3))/2.;
          jacobianMatrix[10][3] = 0;
          jacobianMatrix[10][4] = 0;
          jacobianMatrix[10][5] = 0;
          jacobianMatrix[10][6] = -(mTimestep*(2*q0*Ub - 2*q3*Vb + \
2*q2*Wb))/2.;
          jacobianMatrix[10][7] = -(mTimestep*(2*q1*Ub + 2*(q2*Vb + \
q3*Wb)))/2.;
          jacobianMatrix[10][8] = -(mTimestep*(-2*q2*Ub + 2*q1*Vb + \
2*q0*Wb))/2.;
          jacobianMatrix[10][9] = -(mTimestep*(-2*q3*Ub - 2*q0*Vb + \
2*q1*Wb))/2.;
          jacobianMatrix[10][10] = 1;
          jacobianMatrix[10][11] = 0;
          jacobianMatrix[10][12] = 0;
          jacobianMatrix[11][0] = (mTimestep*(-2*q1*q2 - 2*q0*q3))/2.;
          jacobianMatrix[11][1] = (mTimestep*(-Power(q0,2) + Power(q1,2) - \
Power(q2,2) + Power(q3,2)))/2.;
          jacobianMatrix[11][2] = (mTimestep*(2*q0*q1 - 2*q2*q3))/2.;
          jacobianMatrix[11][3] = 0;
          jacobianMatrix[11][4] = 0;
          jacobianMatrix[11][5] = 0;
          jacobianMatrix[11][6] = (mTimestep*(-2*q3*Ub - 2*q0*Vb + \
2*q1*Wb))/2.;
          jacobianMatrix[11][7] = (mTimestep*(-2*q2*Ub + 2*q1*Vb + \
2*q0*Wb))/2.;
          jacobianMatrix[11][8] = (mTimestep*(-2*q1*Ub - 2*q2*Vb - \
2*q3*Wb))/2.;
          jacobianMatrix[11][9] = (mTimestep*(-2*q0*Ub + 2*q3*Vb - \
2*q2*Wb))/2.;
          jacobianMatrix[11][10] = 0;
          jacobianMatrix[11][11] = 1;
          jacobianMatrix[11][12] = 0;
          jacobianMatrix[12][0] = -(mTimestep*(-2*q0*q2 + 2*q1*q3))/2.;
          jacobianMatrix[12][1] = -(mTimestep*(2*q0*q1 + 2*q2*q3))/2.;
          jacobianMatrix[12][2] = -(mTimestep*(Power(q0,2) - Power(q1,2) - \
Power(q2,2) + Power(q3,2)))/2.;
          jacobianMatrix[12][3] = 0;
          jacobianMatrix[12][4] = 0;
          jacobianMatrix[12][5] = 0;
          jacobianMatrix[12][6] = -(mTimestep*(-2*q2*Ub + 2*q1*Vb + \
2*q0*Wb))/2.;
          jacobianMatrix[12][7] = -(mTimestep*(2*q3*Ub + 2*q0*Vb - \
2*q1*Wb))/2.;
          jacobianMatrix[12][8] = -(mTimestep*(-2*q0*Ub + 2*q3*Vb - \
2*q2*Wb))/2.;
          jacobianMatrix[12][9] = -(mTimestep*(2*q1*Ub + 2*q2*Vb + \
2*q3*Wb))/2.;
          jacobianMatrix[12][10] = 0;
          jacobianMatrix[12][11] = 0;
          jacobianMatrix[12][12] = 1;

          //Solving equation using LU-faktorisation
          mpSolver->solve(jacobianMatrix, systemEquations, stateVark, iter);
          Ub=stateVark[0];
          Vb=stateVark[1];
          Wb=stateVark[2];
          Pb=stateVark[3];
          Qb=stateVark[4];
          Rb=stateVark[5];
          q0=stateVark[6];
          q1=stateVark[7];
          q2=stateVark[8];
          q3=stateVark[9];
          xcg=stateVark[10];
          ycg=stateVark[11];
          zcg=stateVark[12];
          //Expressions
          cal1 = Power(lc1,2)*mCLde1*mS1*qpress*(-Alpha + thetaal1);
          car1 = Power(lc1,2)*mCLde1*mS1*qpress*(-Alpha + thetaar1);
          cal12 = Power(lc12,2)*mCLde12*mS1*qpress*(-Alpha + thetaal12);
          car12 = Power(lc12,2)*mCLde12*mS1*qpress*(-Alpha + thetaar12);
          cal2 = Power(lc2,2)*mCLde2*qpress*S2*(-Alpha + thetaal2);
          car2 = Power(lc2,2)*mCLde2*qpress*S2*(-Alpha + thetaar2);
          cfin = Power(lcfin,2)*mCLdefin*qpress*Sfin*(-Beta + thetafin);
          vx = (Power(q0,2) + Power(q1,2) - Power(q2,2) - Power(q3,2))*Ub + \
2*(q1*q2 - q0*q3)*Vb + 2*(q0*q2 + q1*q3)*Wb;
          vy = 2*(q1*q2 + q0*q3)*Ub + (Power(q0,2) - Power(q1,2) + \
Power(q2,2) - Power(q3,2))*Vb + 2*(-(q0*q1) + q2*q3)*Wb;
          vz = 2*(-(q0*q2) + q1*q3)*Ub + 2*(q0*q1 + q2*q3)*Vb + (Power(q0,2) \
- Power(q1,2) - Power(q2,2) + Power(q3,2))*Wb;
          AlphaAttack = Alpha;
          BetaSlip = Beta;
          altitude = -zcg;
          Phi = Atan2L(2*(q0*q1 + q2*q3),Power(q0,2) - Power(q1,2) - \
Power(q2,2) + Power(q3,2));
          Thetao = ArcSinL(2*(q0*q2 - q1*q3));
          Psi = Atan2L(2*(q1*q2 + q0*q3),Power(q0,2) + Power(q1,2) - \
Power(q2,2) - Power(q3,2));
          gfx = Fx/mass;
          gfy = Fy/mass;
          gfz = Fz/mass;
          Faz = -Liftb - Liftl1 - Liftl2 - Liftr1 - Liftr2;
          Fax = -Dragb - Dragfin - Dragl1 - Dragl2 - Dragr1 - Dragr2;
          CL1 = mCLde1*thetaal1 + mCLde12*thetaal12 + mCLde1*thetaar1 + \
mCLde12*thetaar12 + CLift(Alpha*mdah1 - \
mia1,mCLalpha1,map1,man1,mawp1,mawn1);
          Cd1 = mCd01 + mCdide1*Power(-mde10 + thetaal1,2) - \
mCdide112*(-mde10 + thetaal1)*(-mde120 + thetaal12) + mCdide12*Power(-mde120 \
+ thetaal12,2) + mCdide1*Power(-mde10 + thetaar1,2) - mCdide112*(-mde10 + \
thetaar1)*(-mde120 + thetaar12) + mCdide12*Power(-mde120 + thetaar12,2) + \
CDragInd(Alpha*mdah1 - mia1,mAR1,me1,mCLalpha1,map1,man1,mawp1,mawn1);
          Zcfin = Power(lcfin,2)*mCLdefin*mTimestep*qpress*Sfin;
          Zcal1 = Power(lc1,2)*mCLde1*mS1*mTimestep*qpress;
          Zcar1 = Power(lc1,2)*mCLde1*mS1*mTimestep*qpress;
          Zcal12 = Power(lc12,2)*mCLde12*mS1*mTimestep*qpress;
          Zcar12 = Power(lc12,2)*mCLde12*mS1*mTimestep*qpress;
          Zcal2 = Power(lc2,2)*mCLde2*mTimestep*qpress*S2;
          Zcar2 = Power(lc2,2)*mCLde2*mTimestep*qpress*S2;
        }

        //Calculate the delayed parts
        delayParts1[1] = (-(Fx*mTimestep) + 2*mass*mg0*mTimestep*q0*q2 - \
2*mass*mg0*mTimestep*q1*q3 - 2*mass*Ub - mass*mTimestep*Rb*Vb + \
mass*mTimestep*Qb*Wb - 2*mkground*mTimestep*q0*q2*zcg*onPositive(zcg) + \
2*mkground*mTimestep*q1*q3*zcg*onPositive(zcg))/(2.*mass);
        delayParts2[1] = (-(Fy*mTimestep) - 2*mass*mg0*mTimestep*q0*q1 - \
2*mass*mg0*mTimestep*q2*q3 + mass*mTimestep*Rb*Ub - 2*mass*Vb - \
mass*mTimestep*Pb*Wb + 2*mkground*mTimestep*q0*q1*zcg*onPositive(zcg) + \
2*mkground*mTimestep*q2*q3*zcg*onPositive(zcg))/(2.*mass);
        delayParts3[1] = (-(Fz*mTimestep) - mass*mg0*mTimestep*Power(q0,2) + \
mass*mg0*mTimestep*Power(q1,2) + mass*mg0*mTimestep*Power(q2,2) - \
mass*mg0*mTimestep*Power(q3,2) - mass*mTimestep*Qb*Ub + mass*mTimestep*Pb*Vb \
- 2*mass*Wb + mkground*mTimestep*Power(q0,2)*zcg*onPositive(zcg) - \
mkground*mTimestep*Power(q1,2)*zcg*onPositive(zcg) - \
mkground*mTimestep*Power(q2,2)*zcg*onPositive(zcg) + \
mkground*mTimestep*Power(q3,2)*zcg*onPositive(zcg))/(2.*mass);
        delayParts4[1] = (Iz*Lb*mTimestep + Ixz*mTimestep*Nb - \
2*Power(Ixz,2)*Pb + 2*Ix*Iz*Pb + Ix*Ixz*mTimestep*Pb*Qb - \
Ixz*Iy*mTimestep*Pb*Qb + Ixz*Iz*mTimestep*Pb*Qb - \
Power(Ixz,2)*mTimestep*Qb*Rb + Iy*Iz*mTimestep*Qb*Rb - \
Power(Iz,2)*mTimestep*Qb*Rb)/(2*Power(Ixz,2) - 2*Ix*Iz + Ix*Ixz*mTimestep*Qb \
- Ixz*Iy*mTimestep*Qb + Ixz*Iz*mTimestep*Qb);
        delayParts5[1] = (-(Mb*mTimestep) + Ixz*mTimestep*Power(Pb,2) - \
2*Iy*Qb + Ix*mTimestep*Pb*Rb - Iz*mTimestep*Pb*Rb - \
Ixz*mTimestep*Power(Rb,2))/(2.*Iy);
        delayParts6[1] = (Ixz*Lb*mTimestep + Ix*mTimestep*Nb + \
Power(Ix,2)*mTimestep*Pb*Qb + Power(Ixz,2)*mTimestep*Pb*Qb - \
Ix*Iy*mTimestep*Pb*Qb - 2*Power(Ixz,2)*Rb + 2*Ix*Iz*Rb - \
Ix*Ixz*mTimestep*Qb*Rb + Ixz*Iy*mTimestep*Qb*Rb - \
Ixz*Iz*mTimestep*Qb*Rb)/(2*Power(Ixz,2) - 2*Ix*Iz - Ix*Ixz*mTimestep*Qb + \
Ixz*Iy*mTimestep*Qb - Ixz*Iz*mTimestep*Qb);
        delayParts7[1] = (-4*q0 + mTimestep*Pb*q1 + mTimestep*q2*Qb + \
mTimestep*q3*Rb)/4.;
        delayParts8[1] = (-(mTimestep*Pb*q0) - 4*q1 + mTimestep*q3*Qb - \
mTimestep*q2*Rb)/4.;
        delayParts9[1] = (-4*q2 - mTimestep*Pb*q3 - mTimestep*q0*Qb + \
mTimestep*q1*Rb)/4.;
        delayParts10[1] = (mTimestep*Pb*q2 - 4*q3 - mTimestep*q1*Qb - \
mTimestep*q0*Rb)/4.;
        delayParts11[1] = (-(mTimestep*Power(q0,2)*Ub) - \
mTimestep*Power(q1,2)*Ub + mTimestep*Power(q2,2)*Ub + \
mTimestep*Power(q3,2)*Ub - 2*mTimestep*q1*q2*Vb + 2*mTimestep*q0*q3*Vb - \
2*mTimestep*q0*q2*Wb - 2*mTimestep*q1*q3*Wb - 2*xcg)/2.;
        delayParts12[1] = (-2*mTimestep*q1*q2*Ub - 2*mTimestep*q0*q3*Ub - \
mTimestep*Power(q0,2)*Vb + mTimestep*Power(q1,2)*Vb - \
mTimestep*Power(q2,2)*Vb + mTimestep*Power(q3,2)*Vb + 2*mTimestep*q0*q1*Wb - \
2*mTimestep*q2*q3*Wb - 2*ycg)/2.;
        delayParts13[1] = (2*mTimestep*q0*q2*Ub - 2*mTimestep*q1*q3*Ub - \
2*mTimestep*q0*q1*Vb - 2*mTimestep*q2*q3*Vb - mTimestep*Power(q0,2)*Wb + \
mTimestep*Power(q1,2)*Wb + mTimestep*Power(q2,2)*Wb - \
mTimestep*Power(q3,2)*Wb - 2*zcg)/2.;

        delayedPart[1][1] = delayParts1[1];
        delayedPart[2][1] = delayParts2[1];
        delayedPart[3][1] = delayParts3[1];
        delayedPart[4][1] = delayParts4[1];
        delayedPart[5][1] = delayParts5[1];
        delayedPart[6][1] = delayParts6[1];
        delayedPart[7][1] = delayParts7[1];
        delayedPart[8][1] = delayParts8[1];
        delayedPart[9][1] = delayParts9[1];
        delayedPart[10][1] = delayParts10[1];
        delayedPart[11][1] = delayParts11[1];
        delayedPart[12][1] = delayParts12[1];
        delayedPart[13][1] = delayParts13[1];

        //Write new values to nodes
        //Port Pal1
        (*mpND_cal1)=cal1;
        (*mpND_Zcal1)=Zcal1;
        //Port Par1
        (*mpND_car1)=car1;
        (*mpND_Zcar1)=Zcar1;
        //Port Pal12
        (*mpND_cal12)=cal12;
        (*mpND_Zcal12)=Zcal12;
        //Port Par12
        (*mpND_car12)=car12;
        (*mpND_Zcar12)=Zcar12;
        //Port Pal2
        (*mpND_cal2)=cal2;
        (*mpND_Zcal2)=Zcal2;
        //Port Par2
        (*mpND_car2)=car2;
        (*mpND_Zcar2)=Zcar2;
        //Port Pfin
        (*mpND_cfin)=cfin;
        (*mpND_Zcfin)=Zcfin;
        //outputVariables
        (*mpND_xcg)=xcg;
        (*mpND_ycg)=ycg;
        (*mpND_zcg)=zcg;
        (*mpND_vx)=vx;
        (*mpND_vy)=vy;
        (*mpND_vz)=vz;
        (*mpND_Psi)=Psi;
        (*mpND_Thetao)=Thetao;
        (*mpND_Phi)=Phi;
        (*mpND_Ub)=Ub;
        (*mpND_Vb)=Vb;
        (*mpND_Wb)=Wb;
        (*mpND_Pb)=Pb;
        (*mpND_Qb)=Qb;
        (*mpND_Rb)=Rb;
        (*mpND_q0)=q0;
        (*mpND_q1)=q1;
        (*mpND_q2)=q2;
        (*mpND_q3)=q3;
        (*mpND_AlphaAttack)=AlphaAttack;
        (*mpND_BetaSlip)=BetaSlip;
        (*mpND_altitude)=altitude;
        (*mpND_gfx)=gfx;
        (*mpND_gfy)=gfy;
        (*mpND_gfz)=gfz;
        (*mpND_CL1)=CL1;
        (*mpND_Cd1)=Cd1;
        (*mpND_Fax)=Fax;
        (*mpND_Faz)=Faz;

        //Update the delayed variabels
        mDelayedPart11.update(delayParts1[1]);
        mDelayedPart21.update(delayParts2[1]);
        mDelayedPart31.update(delayParts3[1]);
        mDelayedPart41.update(delayParts4[1]);
        mDelayedPart51.update(delayParts5[1]);
        mDelayedPart61.update(delayParts6[1]);
        mDelayedPart71.update(delayParts7[1]);
        mDelayedPart81.update(delayParts8[1]);
        mDelayedPart91.update(delayParts9[1]);
        mDelayedPart101.update(delayParts10[1]);
        mDelayedPart111.update(delayParts11[1]);
        mDelayedPart121.update(delayParts12[1]);
        mDelayedPart131.update(delayParts13[1]);

     }
};
#endif // AEROAIRCRAFT6DOFS_HPP_INCLUDED
