#ifndef ELECTRICISOURCE_HPP_INCLUDED
#define ELECTRICISOURCE_HPP_INCLUDED

#include <iostream>
//#include <Qt/qdebug.h>
#include "../../HopsanCore/ComponentEssentials.h"
#include "../../HopsanCore/ComponentUtilities.h"
#include <math.h>
#include "matrix.h"

//!
//! @file ElectricIsource.hpp
//! @author Petter Krus <petter.krus@liu.se>
//! @date Sun 12 Jun 2011 13:16:14
//! @brief Source of electric current
//! @ingroup ElectricComponents
//!
//This component is generated by COMPGEN for HOPSAN-NG simulation 
//from 
/*{, C:, Documents and Settings, petkr14, My Documents, \
CompgenNG}/ElectricNG2.nb*/

using namespace hopsan;

class ElectricIsource : public ComponentQ
{
private:
     Port *mpPel1;
     Port *mpPiin;
     int mNstep;
     //Port Pel1 variable
     double uel1;
     double iel1;
     double cel1;
     double Zcel1;
     //Port Piin variable
     double iin;
     //Port Pel1 pointer
     double *mpND_uel1;
     double *mpND_iel1;
     double *mpND_cel1;
     double *mpND_Zcel1;
     //Port Piin pointer
     double *mpND_iin;
     //Delay declarations

public:
     static Component *Creator()
     {
        std::cout << "running ElectricIsource creator" << std::endl;
        return new ElectricIsource("Isource");
     }

     ElectricIsource(const std::string name = "Isource"
                             )
        : ComponentQ(name)
     {
        mNstep=9;

        //Add ports to the component
        mpPel1=addPowerPort("Pel1","NodeElectric");
        mpPiin=addReadPort("Piin","NodeSignal");

        //Register changable parameters to the HOPSAN++ core
     }

    void initialize()
     {
        //Read variable pointers from nodes
        //Port Pel1
        mpND_uel1=getSafeNodeDataPtr(mpPel1, NodeElectric::VOLTAGE);
        mpND_iel1=getSafeNodeDataPtr(mpPel1, NodeElectric::CURRENT);
        mpND_cel1=getSafeNodeDataPtr(mpPel1, NodeElectric::WAVEVARIABLE);
        mpND_Zcel1=getSafeNodeDataPtr(mpPel1, NodeElectric::CHARIMP);
        //Port Piin
        mpND_iin=getSafeNodeDataPtr(mpPiin, NodeSignal::VALUE);
        //Read variables from nodes
        //Port Pel1
        uel1 = (*mpND_uel1);
        iel1 = (*mpND_iel1);
        cel1 = (*mpND_cel1);
        Zcel1 = (*mpND_Zcel1);
        //Port Piin
        iin = (*mpND_iin);



        //Initialize delays
     }
    void simulateOneTimestep()
     {
        //Read variables from nodes
        //Port Pel1
        uel1 = (*mpND_uel1);
        iel1 = (*mpND_iel1);
        cel1 = (*mpND_cel1);
        Zcel1 = (*mpND_Zcel1);
        //Port Piin
        iin = (*mpND_iin);

        //LocalExpressions

        //Expressions
        double iel1 = iin;
        double uel1 = cel1 + iel1*Zcel1;

        //Write new values to nodes
        //Port Pel1
        (*mpND_cel1)=cel1;
        (*mpND_Zcel1)=Zcel1;
        //Port Piin

        //Update the delayed variabels

     }
};
#endif // ELECTRICISOURCE_HPP_INCLUDED
